### PR TITLE
Mount Music Release v1.0.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/481054ceeb850b038f84e3c1efb99c136a557db3..d34161aeb58ec0bd50f4d003331b72401a3dbfc1)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.music_mixer_v1.0.1/Nekres.Music_Mixer-1.0.1.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Music_Mixer` == `Nekres.Music_Mixer`? |
| ✔️ | Manifest and package version match. | `1.0.1` == `1.0.1`? |
| ✔️ | Module and package checksum match. | `0EBB9C1720873CE42D75675AF2478D5AA07DAA31844EDA46F31727C575577523` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**Module Rework**<br>

• Added new and improved custom Mount Music interface.<br>

• Added new Defeated music interface.<br>

• Added game volume fading when custom music is playing for certain states (eg. mounted).<br>

• Removed map wide custom music (for now).<br>

• Removed media widget.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**Music Mixer Module Rework**<br>

• Renamed Music Mixer to Mount Music.<br>

• Added new and improved custom Mount Music interface.<br>

• Added new Defeated music interface.<br>

• Added game volume fading when custom music is playing for certain states (eg. mounted).<br>

• Removed map wide custom music (for now).<br>

• Removed media widget.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**Music Mixer Module Rework**<br>

• Renamed Music Mixer to Mount Music.<br>

• Added new and improved custom Mount Music interface.<br>

• Added new Defeated music interface (Defeated music requires game restart).<br>

• Added game volume fading when custom music is playing for certain states (eg. mounted).<br>

• Removed map wide custom music (for now).<br>

• Removed media widget.<br>

**Pull request merged**
