### PR TITLE
Chat Shorts Release v0.14.2

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/ba30b55abb2dd365c4b62e1f9918e3a04ff446e1..fe6546a140e89b372d0c79806a86e08c5ad8c334)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.chat_shorts_v0.14.2/Nekres.Chat_Shorts-0.14.2.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Chat_Shorts` == `Nekres.Chat_Shorts`? |
| ✔️ | Manifest and package version match. | `0.14.2` == `0.14.2`? |
| ✔️ | Module and package checksum match. | `DF7485228DF5CAF31E263E242F71AD97BD7C6FB27CD0229CCAF7D4E6D832AA6D` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** channel sorting to the quick access menu. Entries are grouped by channel then by most recently used and then by title of the macro.&nbsp;

- **Added** {sector} placeholder which will be replaced with the zone you are currently inside off.



### Bugfixes
- **Fixed** chat being focused but messages not being send.

- **Fixed** whisper lines sometimes not unfocusing the chat after send.


- **Fixed** menus sometimes not showing up.



### Changes
- For maps with a single sector the sector name is used instead of the map name for the {map} placeholder (eg. Fractals).

- Centered the quick access menu's opening position.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** channel sorting to the quick access menu. Entries are grouped by channel then by most recently used and then by title of the macro.&nbsp;

- **Added** {sector} placeholder which will be replaced with the zone you are currently inside off.



### Bugfixes
- **Fixed** chat being focused but messages not being send.

- **Fixed** whisper lines sometimes not unfocusing the chat after being sent.


- **Fixed** menus sometimes not showing up.



### Changes
- For maps with a single sector the sector name is used instead of the map name for the {map} placeholder (eg. Fractals).

- Centered the quick access menu's opening position.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** channel sorting to the quick access menu. Entries are grouped by channel then by most recently used and then by title of the macro.&nbsp;

- **Added** {sector} placeholder which will be replaced with the zone you are currently inside off.



### Bugfixes
- **Fixed** chat being focused but messages not being send.

- **Fixed** whisper lines sometimes not unfocusing the chat after being sent.


- **Fixed** menus sometimes not showing up.



### Changes
- For maps with a single sector the sector name will now be used instead of the map name for the {map} placeholder (eg. Fractals).

- Centered the quick access menu's opening position.

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
