### PR TITLE
Proof Logix Release v2.16.8

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/2a3df23e1015e93f04b8120f8e6095a7b0b91920..4cc2876b8e58c30498a27178934d215552050375)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/killproofmodule_v2.16.8/KillProofModule-2.16.8.bhm |
| ✔️ | Manifest and package namespace match. | `KillProofModule` == `KillProofModule`? |
| ✔️ | Manifest and package version match. | `2.16.8` == `2.16.8`? |
| ✔️ | Module and package checksum match. | `5DDFE57036222A667688B0070123E15B26996C1DBA8872E4BF0EBD31B4C54814` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

<br>• Added ellipsis points to overlong cell text in the Party Table (eg. character names.)<br>

• Added tooltips on mouse hover for Party Table entries (eg. full names).<br>

• Added helpful tooltips to Game Account menu entries.<br>

• Fixed weak visibility of menu icons.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

<br>• Added ellipsis points to overlong text inside cells of the Party Table (eg. character names.)<br>

• Added tooltips on mouse hover for Party Table entries (eg. full names).<br>

• Added helpful tooltips to Game Account menu entries.<br>

• Fixed weak visibility of menu icons.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

<br>• Added ellipsis points to overlong text inside cells of the Party Table (eg. character names).<br>

• Added tooltips on mouse hover for Party Table entries (eg. full names).<br>

• Added helpful tooltips to Game Account menu entries.<br>

• Fixed weak visibility of menu icons.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>• Added ellipsis points to overlong text inside cells of the Party Table (eg. character names).<br>

• Added tooltips on mouse hover for Party Table entries (eg. full names).<br>

• Added helpful tooltips to Game Account menu entries.<br>

• Fixed weak visibility of menu icons.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**&nbsp;&nbsp;<br>

<br>• Added ellipsis points to overlong text inside cells of the Party Table (eg. character names).<br>

• Added tooltips on mouse hover for Party Table entries (eg. full names).<br>

• Added helpful tooltips to Game Account menu entries.<br>

• Fixed weak visibility of menu icons.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** ellipsis points to overlong text inside cells of the Party Table (eg. character names).

- **Added** tooltips on mouse hover for Party Table entries (eg. full names).


- **Added** helpful tooltips to Game Account menu entries.



### Bugfixes
- **Fixed** weak visibility of menu icons.

**Pull request merged**
