### PR TITLE
Proof Logix Release v2.17.4

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/a33bc3a6cfb10e98616c24dff6a8203cadceeab8..39ae2b8b572123844efa8ff6f9a1d45ffcb449df)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/killproofmodule_v2.17.4/KillProofModule-2.17.4.bhm |
| ✔️ | Manifest and package namespace match. | `KillProofModule` == `KillProofModule`? |
| ✔️ | Manifest and package version match. | `2.17.4` == `2.17.4`? |
| ✔️ | Module and package checksum match. | `3DC2425357A266132A325C0F8673D7AC9B35180FD6EF4F4F964C125AAE926E35` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>• Fixed a crash when using Smart Ping with Mouse 1 and 2 at the same time.<br>

**Comment by agaertner** [comment]
Oversight

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**&nbsp;&nbsp;<br>

<br>• Fixed a crash when using Smart Ping with Mouse 1 and 2 at the same time.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Hotfix
- **Fixed** a crash when using Smart Ping with Mouse 1 and 2 at the same time.

**Pull request merged**
