### PR TITLE
Chat Shorts Release v0.11.5

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/6bb13b031d4ab0e840723fca365280bede6d2740..7990e3ee26ce7b4cea639518337650b585236b07)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.chat_shorts_v0.11.5/Nekres.Chat_Shorts-0.11.5.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Chat_Shorts` == `Nekres.Chat_Shorts`? |
| ✔️ | Manifest and package version match. | `0.11.5` == `0.11.5`? |
| ✔️ | Module and package checksum match. | `E1754975F7A1531D497E0CEE7BC426E19EF33FA79E7E5CD2D77A9B61EB8A6B05` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** Quick Access menu to activate macros by mouse click.

- **Added** control options category


- **Added** "Open Quick Access" key binding setting.


- **Added** Whisper target channel with recipient input field.


- **Added** "Broadcast to Squad" toggle to the [Squad] target channel.


### Bugfixes
- **Fixed** Push-To-Talk key binding not working on first module start.

- **Fixed** some French translations (Thanks to&nbsp;N̴a̵r̶u̸ (&lt;@363654699964039178&gt;))


- **Fixed** module freeze when no device is selected.


- **Fixed** key bindings ignoring active map restrictions.


- **Fixed** key bindings being enabled by default when loaded.


- **Fixed** endless loop when binding a macro to LCtrl, A, V, Del or Enter.


- **Fixed** bindings activating while busy (not in-game, text field already focused, ...)


- **Fixed** missing translations in the default module settings panel.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** Quick Access menu to activate macros by mouse click.

- **Added** control options category


- **Added** "Open Quick Access" key binding setting.


- **Added** Whisper target channel with recipient input field.


- **Added** "Broadcast to Squad" toggle to the [Squad] target channel.


### Bugfixes
- **Fixed** Push-To-Talk key binding not working on first module start.

- **Fixed** some French translations (Thanks to&nbsp;N̴a̵r̶u̸ (&lt;@363654699964039178&gt;))


- **Fixed** module freeze when no device is selected.


- **Fixed** key bindings ignoring active map restrictions.


- **Fixed** key bindings being enabled by default when loaded.


- **Fixed** endless loop when binding a macro to LCtrl, A, V, Del or Enter.


- **Fixed** bindings activating while busy (not in-game, text field already focused, ...)


- **Fixed** missing translations in the default module settings panel.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** Quick Access menu to activate macros by mouse click.

- **Added** control options category.


- **Added** "Open Quick Access" key binding setting.


- **Added** Whisper target channel with recipient input field.


- **Added** "Broadcast to Squad" toggle to the [Squad] target channel.


### Bugfixes
- **Fixed** Push-To-Talk key binding not working on first module start.

- **Fixed** some French translations (Thanks to&nbsp;N̴a̵r̶u̸ (&lt;@363654699964039178&gt;))


- **Fixed** module freeze when no device is selected.


- **Fixed** key bindings ignoring active map restrictions.


- **Fixed** key bindings being enabled by default when loaded.


- **Fixed** endless loop when binding a macro to LCtrl, A, V, Del or Enter.


- **Fixed** bindings activating while busy (not in-game, text field already focused, ...)


- **Fixed** missing translations in the default module settings panel.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** Quick Access menu to activate macros by mouse click.

- **Added** control options category.


- **Added** "Open Quick Access" key binding setting.


- **Added**&nbsp;support for the Whisper target channel with a recipient input field.&nbsp;


- **Added** "Broadcast to Squad" toggle to the [Squad] target channel of a line.


### Bugfixes
- **Fixed** Push-To-Talk key binding not working on first module start.

- **Fixed** some French translations (Thanks to&nbsp;N̴a̵r̶u̸ (&lt;@363654699964039178&gt;))


- **Fixed** module freeze when no device is selected.


- **Fixed** key bindings ignoring active map restrictions.


- **Fixed** key bindings being enabled by default when loaded.


- **Fixed** endless loop when binding a macro to LCtrl, A, V, Del or Enter.


- **Fixed** bindings activating while busy (not in-game, text field already focused, ...)


- **Fixed** missing translations in the default module settings panel.

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** Quick Access menu to activate macros by mouse click.

- **Added** control options category.


- **Added** "Open Quick Access" key binding setting.


- **Added**&nbsp;support for the Whisper target channel with a recipient input field.&nbsp;


- **Added** "Broadcast to Squad" toggle to the [Squad] target channel of a line.


### Bugfixes
- **Fixed** Push-To-Talk key binding not working on first module start.

- **Fixed** some French translations (Thanks to&nbsp;N̴a̵r̶u̸)


- **Fixed** module freeze when no device is selected.


- **Fixed** key bindings ignoring active map restrictions.


- **Fixed** key bindings being enabled by default when loaded.


- **Fixed** endless loop when binding a macro to LCtrl, A, V, Del or Enter.


- **Fixed** bindings activating while busy (not in-game, text field already focused, ...)


- **Fixed** missing translations in the default module settings panel.

**Pull request merged**
