### PR TITLE
Event Table Release v3.14.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Estreya

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/ee181c8329f36c377d70e48297830e862df116ad..a8da53c21305c520e7b32ef62669a2185a7788b2)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/estreya.bh.eventtable_v3.14.0/estreya.bh.eventTable-3.14.0.bhm |
| ✔️ | Manifest and package namespace match. | `estreya.bh.eventTable` == `estreya.bh.eventTable`? |
| ✔️ | Manifest and package version match. | `3.14.0` == `3.14.0`? |
| ✔️ | Module and package checksum match. | `41BF81CDE56245A842002608AD5144BA08845A6C4859CCE3669AE71A210D7390` |

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Bugfixes**<br>

- Fixed loading spinner showing when moved into Bag of Holding


**Features**<br>

- Now showing events on the (mini-)map

- Now showing event information in the in-game world near the events locations


**BREAKING CHANGES FOR CONTEXT**<br>

The AddEvent struct has the following changes:<br>

- Removed property "Locations"

- Added property "Location"


**Info for WINE users**<br>

The usage of the module on WINE as provided via the normal blish repo causes blish to crash.<br>

The reason for that is the usage of the windows foundation universal api contract for OS notifications which is not fully implemented in WINE.<br>

If you want to use the module on WINE please use this custom build: [CLICK HERE](https://files.estreya.de/blish-hud/event-table/releases/Estreya.BlishHUD.EventTable_3.14.0-WINE.bhm)<br>

*You CAN'T use the update feature for modules when using that custom build.*<br>

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Bugfixes**<br>

- Fixed loading spinner showing when moved into Bag of Holding


**Features**<br>

- Now showing events on the (mini-)map

- Now showing event information in the in-game world near the events locations


*Disclaimer: There are not yet all events shown*<br>

**BREAKING CHANGES FOR CONTEXT**<br>

The AddEvent struct has the following changes:<br>

- Removed property "Locations"

- Added property "Location"


**Info for WINE users**<br>

The usage of the module on WINE as provided via the normal blish repo causes blish to crash.<br>

The reason for that is the usage of the windows foundation universal api contract for OS notifications which is not fully implemented in WINE.<br>

If you want to use the module on WINE please use this custom build: [CLICK HERE](https://files.estreya.de/blish-hud/event-table/releases/Estreya.BlishHUD.EventTable_3.14.0-WINE.bhm)<br>

*You CAN'T use the update feature for modules when using that custom build.*<br>

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Bugfixes**<br>

- Fixed loading spinner showing when moved into Bag of Holding


**Features**<br>

- Now showing events on the (mini-)map

- Now showing event information in the in-game world near the events locations


*Disclaimer: There are not yet all events shown*<br>

**BREAKING CHANGES FOR CONTEXT**<br>

The AddEvent struct has the following changes:<br>

- Removed property "Locations"

- Added property "Location"


**Info for WINE users**<br>

The usage of the module on WINE as provided via the normal blish repo causes blish to crash.<br>

The reason for that is the usage of the windows foundation universal api contract for OS notifications which is not fully implemented in WINE.<br>

If you want to use the module on WINE please use this custom build: [CLICK HERE](https://files.estreya.de/blish-hud/event-table/releases/Estreya.BlishHUD.EventTable_3.14.0-WINE.bhm)<br>

*You CAN'T use the update feature for modules when using that custom build.*<br>

**Comment by BlishHUD** [comment]
Release notes updated by Freesnöw.<br><br>
**Bugfixes**<br>

- Fixed loading spinner showing when moved into Bag of Holding


**Features**<br>

- Now showing events on the (mini-)map

- Now showing event information in the in-game world near the events locations


*Disclaimer: There are not yet all events shown*<br>

**BREAKING CHANGES FOR CONTEXT**<br>

The AddEvent struct has the following changes:<br>

- Removed property "Locations"

- Added property "Location"


**Info for WINE users**<br>

The usage of the module on WINE as provided via the normal blish repo causes blish to crash.<br>

The reason for that is the usage of the windows foundation universal api contract for OS notifications which is not fully implemented in WINE.<br>

If you want to use the module on WINE please use this custom build: [CLICK HERE](https://files.estreya.de/blish-hud/event-table/releases/Estreya.BlishHUD.EventTable_3.14.0-WINE.bhm)<br>

*You CAN'T use the update feature for modules when using that custom build.*<br>

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
