### PR TITLE
Add Mistwar v0.4.0

### PR DESCRIPTION
**Pull request by agaertner**

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/7f195c9282a7ba58494d56642e0737bfe3aba53f..7b7167488edc54b010dd537892a02c4168ce45c6)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/agaertner/Blish-HUD-Modules-Releases/releases/download/bh.blishhud%3E%3D0.11.1-ci.64/Mistwar.v0.4.0.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Mistwar` == `Nekres.Mistwar`? |
| ✔️ | Manifest and package version match. | `0.4.0` == `0.4.0`? |
| ✔️ | Module and package checksum match. | `A9713DCE1A3F5B2DCA85799B78CEE8B9CBEAED20C0234E485B38C9B88253B159` |

**Comment by agaertner** [comment]
Stop wait

**Comment by dlamkins** [comment]
Okay, waiting.  You caught me just in time.  🙂

**Comment by agaertner** [comment]
Now you can. Accidentally used the wrong identity for the commit and had to remove it from history.

**Pull request merged**
