### PR TITLE
Special Forces Release v0.4.12

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/74b8b7e0b0d996b491a7b5e8f7dd6461a7c14166..b73fe54f82bb085f6a2fe3fcccc22c79d5e863af)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.rotationtrainer_v0.4.12/Nekres.RotationTrainer-0.4.12.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.RotationTrainer` == `Nekres.RotationTrainer`? |
| ✔️ | Manifest and package version match. | `0.4.12` == `0.4.12`? |
| ✔️ | Module and package checksum match. | `C293C54A68305566278F77888598513542202E58EC545BDBE695ADDD9BE0EF3A` |

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
@Freesnöw#0001 with the fast fingers. Couldn't wait for me to attach some patch notes! :AAAURENE: (I was in the bathroom while it uploaded :leaky:) ... Anyway:<br><br>- **Fixed** a crash on rotation start.&nbsp;<br>

:maraca:<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
@Freesnöw#0001 with the fast fingers. Couldn't wait for me to attach some patch notes! ... Anyway:<br><br>- **Fixed** a crash on rotation start.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
Freesnöw with the fast fingers. Couldn't wait for me to attach some patch notes! ... Anyway:<br><br>- **Fixed** a crash on rotation start.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
Freesnöw with the fast fingers. Couldn't wait for me to attach some patch notes! ... Anyway:&nbsp;&nbsp;<br>&nbsp;&nbsp;<br>- **Fixed** a crash on rotation start.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
Freesnöw with the fast fingers. Couldn't wait for me to attach some patch notes! ... Anyway:&nbsp;&nbsp;<br>&nbsp;&nbsp;<br>- **Fixed** a crash on rotation start.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
Freesnöw with the fast fingers. Couldn't wait for me to attach some patch notes! ... Anyway:&nbsp;&nbsp;<br>&nbsp;&nbsp;<br>- **Fixed** a crash on rotation start.<br>

**Pull request merged**
