### PR TITLE
Farming Tracker Release v3.0.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Ecksofa

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/e1acdb0c815826261015cd81c3cb7fa14845b857..b31f581f0f4795cc770193c12d0283533cfd56e9)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/ecksofa.farmingtracker_v3.0.0/ecksofa.farmingtracker-3.0.0.bhm |
| ✔️ | Manifest and package namespace match. | `ecksofa.farmingtracker` == `ecksofa.farmingtracker`? |
| ✔️ | Manifest and package version match. | `3.0.0` == `3.0.0`? |
| ✔️ | Module and package checksum match. | `9BC7A3D633738B8ECA10BD1A071B48F5EE36B6EFDFD5C71A2FE929D4B00C639F` |

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
Requires **Blish HUD 1.1.1 **from https://blishhud.com/. At the moment older Blish versions will NOT offer a self update to Blish 1.1.1. You have to manually download Blish 1.1.1 from the website.<br>

**New**<br>

- new setting to change what is displayed in the profit window: profit, profit per hour or both.<br>

- profit window has a tooltip showing profit per hour. This might be expanded in the future to show more information.<br>

- profit label settings do not affect profit labels in the farming tracker window anymore. They only affect the profit window now. These settings are now part of the profit window settings. <br>

**Fixed**<br>

- csv file export button created invalid csv files when an item name contained comma and/or quotes.<br>

- csv file export button tooltip showed wrong file path when the blish settings are not at their default path Documents\Guild Wars 2\addons\blishhud\.<br>

**Internal / Minor**<br>

- calculate profits only once for the whole module and not once per profit display.<br>

- use interval logic from sessionTracker module instead of a runningTime for automatic reset checks and saving the farming duration .<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
Requires **Blish HUD 1.1.1 **from https://blishhud.com/. At the moment older Blish versions will NOT offer a self update to Blish 1.1.1. You have to manually download Blish 1.1.1 from the website.<br>

**New**<br>

- new setting to change what is displayed in the profit window: profit, profit per hour or both.<br>

- profit window has a tooltip showing profit per hour. This might be expanded in the future to show more information.<br>

- profit label settings do not affect profit labels in the farming tracker window anymore. They only affect the profit window now. These settings are now part of the profit window settings. <br>

**Fixed**<br>

- csv file export button created invalid csv files when an item name contained comma and/or quotes.<br>

- csv file export button tooltip showed wrong file path when the blish settings are not at their default path Documents\Guild Wars 2\addons\blishhud\.<br>

**Internal / Minor**<br>

- calculate profits only once for the whole module and not once per profit display.<br>

- use interval logic from sessionTracker module instead of a runningTime for automatic reset checks, saving the farming duration and updating profit per hour.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**New**<br>

- new setting to change what is displayed in the profit window: profit, profit per hour or both.<br>

- profit window has a tooltip showing profit per hour. This might be expanded in the future to show more information.<br>

- profit label settings do not affect profit labels in the farming tracker window anymore. They only affect the profit window now. These settings are now part of the profit window settings. <br>

**Fixed**<br>

- csv file export button created invalid csv files when an item name contained comma and/or quotes.<br>

- csv file export button tooltip showed wrong file path when the blish settings are not at their default path Documents\Guild Wars 2\addons\blishhud\.<br>

**Internal / Minor**<br>

- calculate profits only once for the whole module and not once per profit display.<br>

- use interval logic from sessionTracker module instead of a runningTime for automatic reset checks, saving the farming duration and updating profit per hour.<br>

**Pull request merged**
