### PR TITLE
Regions of Tyria Release v0.10.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/42dba2369ca4f03f2cab660e706d65cfd11b9d54..580d9314c10c4d7530f5251171a3ac36e7f3f0dc)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.regions_of_tyria_v0.10.1/Nekres.Regions_Of_Tyria-0.10.1.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Regions_Of_Tyria` == `Nekres.Regions_Of_Tyria`? |
| ✔️ | Manifest and package version match. | `0.10.1` == `0.10.1`? |
| ✔️ | Module and package checksum match. | `4EF179E2C2411582AB0103E7E9DA186C86B108944BC3CF7529A9A715323BBC86` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** reveal and vanish sounds.

- **Added**&nbsp;Mute Reveal and Mute Vanish settings.


### Changes
- **Changed** zone detection to ignore walking back and forth between the same two zones.


### Bugfixes
- **Fixed** crash notifications try to load when app is closing.

- **Fixed** lines overlapping for single map or sector names that stretch across multiple lines such as&nbsp;*Mordant Crescent&lt;br&gt;Great Hall.*

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** reveal and vanish sounds.

- **Added**&nbsp;Mute Reveal and Mute Vanish settings.


### Changes
- **Changed** zone detection to ignore walking back and forth between the same two zones.


### Bugfixes
- **Fixed** crash notifications try to load when app is closing.

- **Fixed** lines overlapping for single map or sector names that stretch across multiple lines such as&nbsp;*Mordant Crescent\&lt;br\&gt;Great Hall.*

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** reveal and vanish sounds.

- **Added**&nbsp;Mute Reveal and Mute Vanish settings.


### Changes
- **Changed** zone detection to ignore walking back and forth between the same two zones.


### Bugfixes
- **Fixed** crash notifications try to load when app is closing.

- **Fixed** lines overlapping for single map or sector names that stretch across multiple lines such as "*Mordant Crescent\&lt;br\&gt;Great Hall".*

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** reveal and vanish sounds.

- **Added**&nbsp;Mute Reveal and Mute Vanish settings.


### Changes
- **Changed** zone detection to ignore walking back and forth between the same two zones.


### Bugfixes
- **Fixed** crash notifications try to load when app is closing.

- **Fixed** lines overlapping for single map or sector names that stretch across multiple lines such as "*Mordant Crescent*\&lt;br\&gt;*Great Hall*"*.*

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** reveal and vanish sounds.

- **Added**&nbsp;Mute Reveal and Mute Vanish settings.


### Changes
- **Changed** zone detection to ignore walking back and forth between the same two zones.


### Bugfixes
- **Fixed** crash notifications try to load when app is closing.

- **Fixed** lines overlapping for single map or sector names that stretch across multiple lines such as "*Mordant Crescent*&lt;br&gt;*Great Hall*"*.*

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** reveal and vanish sounds.

- **Added**&nbsp;Mute Reveal and Mute Vanish settings.


### Changes
- **Changed** zone detection to ignore walking back and forth between the same two zones.


### Bugfixes
- **Fixed** crash when notifications try to load the moment the app is closing.

- **Fixed** lines overlapping for single map or sector names that stretch across multiple lines such as "*Mordant Crescent*&lt;br&gt;*Great Hall*"*.*

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
