### PR TITLE
Events and Metas Observer Release v1.0.2

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Freesnöw

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/e4de5396fc0b39ea91cd463834c1488e16af0736..fac3d4804feafb903ec04cc50cb44237538ffc4b)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/bh.general.events_v1.0.2/bh.general.events-1.0.2.bhm |
| ✔️ | Manifest and package namespace match. | `bh.general.events` == `bh.general.events`? |
| ✔️ | Manifest and package version match. | `1.0.2` == `1.0.2`? |
| ✔️ | Module and package checksum match. | `E19AE02EAEA70DD9968B9FFADE5433B49A4E7DFFD85F64B5C93B4CAF2F91A34D` |

**Comment by BlishHUD** [comment]
Release notes updated by Freesnöw.<br><br>
Added Convergences (Public) event.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Freesnöw.<br><br>
Added [Convergences (Public)](https://wiki.guildwars2.com/wiki/Convergences) event.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Freesnöw.<br><br>
Added [Convergences (Public)](https://wiki.guildwars2.com/wiki/Convergences) event (thanks gamingrobot!)<br>

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
