### PR TITLE
Quick Surrender Release v0.2.7

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/9413df69c60d516d371bc015c3cdd3f6be182803..c7966f2e0fe99c2d10899aa3f02389aa8afc5c20)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.quick_surrender_module_v0.2.7/Nekres.Quick_Surrender_Module-0.2.7.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Quick_Surrender_Module` == `Nekres.Quick_Surrender_Module`? |
| ✔️ | Manifest and package version match. | `0.2.7` == `0.2.7`? |
| ✔️ | Module and package checksum match. | `6E050FB3D1C6E949BA81DE79F9993A055FC8A93179775487F321A3D25255D0C2` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Changes
- **Increased** cooldown to 5 seconds in accordance to the duration of invulnerability buff applied after resurrection.


### Hotfix
- **Fixed** French tooltip text being cut off at the bottom.

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Changes
- **Increased** cooldown to 5 seconds in accordance to the duration of&nbsp; the invulnerability buff applied after resurrection.


### Hotfix
- **Fixed** French tooltip text being cut off at the bottom.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Changes
- **Increased** cooldown to 5 seconds in accordance to the duration of the invulnerability buff applied after resurrection.


### Hotfix
- **Fixed** French tooltip text being cut off at the bottom.

**Pull request merged**
