### PR TITLE
Mount Music Release v1.7.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/6c13a59e99ad872e6cf875dee1671a7ade3e2a83..1fcaaec785e584832d5c4966653dce5010970acd)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.music_mixer_v1.7.0/Nekres.Music_Mixer-1.7.0.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Music_Mixer` == `Nekres.Music_Mixer`? |
| ✔️ | Manifest and package version match. | `1.7.0` == `1.7.0`? |
| ✔️ | Module and package checksum match. | `B969BBF5F7A57BBA5BA8B84D4D3DFC363B24FD93BCCED0BC3CD933A71D80FE2B` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting *Automatically update default music* (Only on module start and only if there is new music available.).

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Feature
- **Added** setting *Automatically update default music* (Only on module start and only if there is new music available.).

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Feature
- **Added** setting *Automatically update default music* (Only checks for new default music on module start.).

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
