### PR TITLE
Session Tracker Release v6.0.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Ecksofa

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/e420e55e08bfa96579c42007756aef0f4aaf6ea0..5c77243ff8a423c7f851367d0f1a810c349a2638)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/ecksofa.sessiontracker_v6.0.0/ecksofa.sessiontracker-6.0.0.bhm |
| ✔️ | Manifest and package namespace match. | `ecksofa.sessiontracker` == `ecksofa.sessiontracker`? |
| ✔️ | Manifest and package version match. | `6.0.0` == `6.0.0`? |
| ✔️ | Module and package checksum match. | `BDD520B62CC7B42B862CD13C2AB3D5D34C454C19DC27922F3E39D4E089909FBB` |

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**Fixed**<br>

- when fixed-height-setting was enabled, the scroll bar was suddenly disabled while scrolling the stats when a session reset/update happened<br>

- when fixed-height-setting was enabled while no stats are visible, the module crashed because it could not find the scroll bar. This caused crashs on module startup and when enabling the fixed-height-setting while no stats are displayed.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**Fixed**<br>

- when fixed-height-setting was enabled, the scroll bar was suddenly disabled while scrolling the stats when a session reset/update happened<br>

- when fixed-height-setting was enabled while no stats are visible, the module crashed because it could not find the scroll bar. This caused crashes on module startup and when enabling the fixed-height-setting while no stats are displayed.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**Hint**<br>- this version stays visible for blish 1.0.0 users. It will be hidden, when a non-prerelease blish version &gt;=1.1.1 is released.<br><br>**Fixed**<br>

- when fixed-height-setting was enabled, the scroll bar was suddenly disabled while scrolling the stats when a session reset/update happened<br>

- when fixed-height-setting was enabled while no stats are visible, the module crashed because it could not find the scroll bar. This caused crashes on module startup and when enabling the fixed-height-setting while no stats are displayed.<br>

**Pull request merged**
