### PR TITLE
Builds Manager Release v0.0.5

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Kenedia

### CODE REVIEW

**Comment by dlamkins** [comment]
- Ctrl for rebuilding the UI needs to be disabled for your release builds.
- Strange behavior when switching while a popout is active: https://gfycat.com/fakeresponsibleanemonecrab
- I'm not sure what right-click in the Gear tab is meant to do.  It appears to just rebuild the UI (I guess it's pressing CTRL in the process).
- The first time I tried right-clicking in the Gear tab, I received a .NET exception that didn't leave a trace but said Access was denied and Blish HUD crashed.  If you're interacting with the clipboard (preferably through the Async clipboard service util we expose), I'd recommend catching any errors if there is a chance they bubble up.
- Is revenant properly supported now?  If not, I would recommend removing it (or graying it out with a tooltip saying it's not ready) to avoid the questions/confusion that is sure to follow.

Module looks beautiful, though.  Folks are going to absolutely love this.

**Comment by dlamkins** [comment]
Exception seen by the module after it was disabled (it appears the CTRL keybinding wasn't disabled on unload - perhaps this won't be relevant once it's disabled in release builds):

```
15:48:56.5767 | FATAL | Blish_HUD.DebugService | Blish HUD encountered a fatal crash!
System.NullReferenceException: Object reference not set to an instance of an object.
   at Kenedia.Modules.BuildsManager.Template..ctor(String path) in C:\BhApps\BhudRequestFor\work\1261_fbfbd7df-c8e7-4e34-aace-cf570cef2108\Classes\BuildTemplate.cs:line 337
   at Kenedia.Modules.BuildsManager.BuildsManager.LoadTemplates() in C:\BhApps\BhudRequestFor\work\1261_fbfbd7df-c8e7-4e34-aace-cf570cef2108\BuildsManager.cs:line 264
   at Kenedia.Modules.BuildsManager.BuildsManager.CreateUI() in C:\BhApps\BhudRequestFor\work\1261_fbfbd7df-c8e7-4e34-aace-cf570cef2108\BuildsManager.cs:line 943
   at Kenedia.Modules.BuildsManager.BuildsManager.ReloadKey_Activated(Object sender, EventArgs e) in C:\BhApps\BhudRequestFor\work\1261_fbfbd7df-c8e7-4e34-aace-cf570cef2108\BuildsManager.cs:line 248
   at Blish_HUD.Input.KeyBinding.Fire() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Input\Keyboard\KeyBinding.cs:line 101
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Blish_HUD.Input.KeyboardHandler.Update() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Input\Keyboard\KeyboardHandler.cs:line 130
   at Blish_HUD.BlishHud.Update(GameTime gameTime) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\BlishHud.cs:line 128
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Blish_HUD.Program.Main(String[] args) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Program.cs:line 97
```

**Comment by dlamkins** [comment]
Exception thrown by the AsyncWIndowsClipboard service it looks like:

```cs
15:43:14.2680 | WARN  | Kenedia.Modules.BuildsManager.BuildsManager | Failed to set clipboard text to ""!
System.ArgumentException: Value cannot be null or empty.
Parameter name: text
   at AsyncWindowsClipboard.Clipboard.Text.UnicodeTextService.GetBytes(String text) in C:\Dev\undergroundwires\AsyncWindowsClipboard\src\AsyncWindowsClipboard\Clipboard\Text\UnicodeTextService.cs:line 42
   at AsyncWindowsClipboard.Modifiers.Writers.StringWriter.Write(IClipboardWritingContext context, String data) in C:\Dev\undergroundwires\AsyncWindowsClipboard\src\AsyncWindowsClipboard\Modifiers\Writers\StringWriter.cs:line 18
   at AsyncWindowsClipboard.Modifiers.Writers.Base.ClipboardWriterBase`1.<>c__DisplayClass0_0.<WriteAsync>b__0() in C:\Dev\undergroundwires\AsyncWindowsClipboard\src\AsyncWindowsClipboard\Modifiers\Writers\Base\ClipboardWriterBase.cs:line 40
   at AsyncWindowsClipboard.Modifiers.Helpers.TaskHelper.<>c__DisplayClass0_0`1.<StartStaTask>b__0() in C:\Dev\undergroundwires\AsyncWindowsClipboard\src\AsyncWindowsClipboard\Modifiers\Helpers\TaskHelper.cs:line 26
   ```
   
   Provably should short-circuit exit any calls prior to attempting to set the clipboard to "".

**Comment by KenediaDev** [comment]
- [x] Ctrl for rebuilding the UI needs to be disabled for your release builds.
`Removed!`

- [x] Strange behavior when switching while a popout is active: https://gfycat.com/fakeresponsibleanemonecrab
`Changed to close on Template switch & clicking anywhere but the control`

- [x] I'm not sure what right-click in the Gear tab is meant to do.  It appears to just rebuild the UI (I guess it's pressing CTRL in the process).
`Working as intended, it copies the stat/upgrades name to your clipboard. It is in your case indeed the problem with CTRL triggering the Rebuild. Resetting the settings should fix, as the rebuild key is set to none by default now.`


- [x] Is revenant properly supported now?  If not, I would recommend removing it (or graying it out with a tooltip saying it's not ready) to avoid the questions/confusion that is sure to follow.
`No its not yet fully supported. Disclaimer added for Rev Builds`
image

- [x] Module looks beautiful, though. Folks are going to absolutely love this.
`Thanks a lot :D`

- [x] Exception thrown by the AsyncWIndowsClipboard service
The first time I tried right-clicking in the Gear tab, I received a .NET exception that didn't leave a trace but said Access was denied and Blish HUD crashed.  If you're interacting with the clipboard (preferably through the Async clipboard service util we expose), I'd recommend catching any errors if there is a chance they bubble up.
`Checking the clipboard content if its null / "" and wrapped in try/catch`

**Pull request closed without merging**
