### PR TITLE
Mount Music Release v1.4.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/10a7be7885273fd800a5d23af9bd2b31c8cd52b9..451c0e7ac5490b6ab30eac974038aecce8aa088b)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.music_mixer_v1.4.0/Nekres.Music_Mixer-1.4.0.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Music_Mixer` == `Nekres.Music_Mixer`? |
| ✔️ | Manifest and package version match. | `1.4.0` == `1.4.0`? |
| ✔️ | Module and package checksum match. | `56BC88830FECD7AC372F1B5B5EA60585CE4A8EC545CF1663E1842CF26025B181` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
Feature<br>

- **Added** default playlist import on first start up of the module.

- **Added** "Copy Playlists to Clipboard" button to settings.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**Feature**<br>

- **Added** default playlist import on first start up of the module.

- **Added** "Copy Playlists to Clipboard" button to settings.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**Features**<br>

- **Added** default playlist import on first start up of the module.

- **Added** "Copy Playlists to Clipboard" button to settings.

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
