### PR TITLE
Mount Music Release v1.2.6

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/b7b19416eb0be32720f87a7ab8bae0eff92fbce1..10a7be7885273fd800a5d23af9bd2b31c8cd52b9)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.music_mixer_v1.2.6/Nekres.Music_Mixer-1.2.6.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Music_Mixer` == `Nekres.Music_Mixer`? |
| ✔️ | Manifest and package version match. | `1.2.6` == `1.2.6`? |
| ✔️ | Module and package checksum match. | `172AFD6CC1E29D8F9EF8C9ED42664D6828F8740239B3DC7EBCA2A285E50BD252` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Hotifx
- **Fixed** crash when opening settings when an output device or audiotrack is unavailable.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Hotifx
- **Fixed** crash when opening settings when an output device or audiotrack is unavailable.

- **Fixed** music not pausing when game volume is 0 (v1.2.5)

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Hotifx
- **Fixed** crash when opening settings when an output device or audiotrack is unavailable.

- **Fixed** music not pausing when game volume is 0 (v1.2.5).

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Hotfix
- **Fixed** crash when opening settings when an output device or audiotrack is unavailable.

- **Fixed** music not pausing when game volume is 0 (v1.2.5).

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
