### PR TITLE
Blishpad 0.1.2

### PR DESCRIPTION
**Pull request by Snaid1**

### CODE REVIEW

**Comment by dlamkins** [comment]
Great - I'll try to get this reviewed tonight and will let you know if there is anything else that needs completed.  👍

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/7f195c9282a7ba58494d56642e0737bfe3aba53f..e29b8c707f62658b58d981f3973e65ad5f1a1405)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/Snaid1/BHUD-Blishpad/releases/download/0.1.2/Blishpad.bhm |
| ✔️ | Manifest and package namespace match. | `Snaid1.Blishpad` == `Snaid1.Blishpad`? |
| ✔️ | Manifest and package version match. | `0.1.2` == `0.1.2`? |
| ✔️ | Module and package checksum match. | `995A840DE116AB0805655673E1C4930851149861252974B00F9DE4ACEF762578` |

**Comment by dlamkins** [comment]
Hey, only thing that I'm immediately seeing is that there is a cs file in your ref folder that looks to be there by mistake.  Not technically an issue, but I suspect is likely to get the assembly flagged by anti-virus for dynamic code stuff.

Think you could rebuild with that cs file moved to not be included in the ref and resubmit?  The rest looks like it was done perfectly.  👍

**Comment by Snaid1** [comment]
Can do. That file ended up there by mistake. I've actually already moved it
in the branch I'm working on currently. I'll let you know when that is
taken care of on github.

**Comment by Snaid1** [comment]
@dlamkins Rebuilt with the cs file moved. Should be ready to go now. I pushed a commit with the updated hash

**Comment by dlamkins** [comment]
Looks great!

**Pull request merged**
