### PR TITLE
Session Tracker Release v7.0.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Ecksofa

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/5c77243ff8a423c7f851367d0f1a810c349a2638..5b341a27b076d869e6f75d6095ddae0af159999c)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/ecksofa.sessiontracker_v7.0.0/ecksofa.sessiontracker-7.0.0.bhm |
| ✔️ | Manifest and package namespace match. | `ecksofa.sessiontracker` == `ecksofa.sessiontracker`? |
| ✔️ | Manifest and package version match. | `7.0.0` == `7.0.0`? |
| ✔️ | Module and package checksum match. | `67898CEAF3476C2CA9B14A2EA36F69EE22BD25DCCBEF4A6EAD90E54E7B51644C` |

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**New**<br>

- session value per hour can be displayed. "/hour" unit text can be changed. This does not affect the stat tooltip.<br>

- separator between values can be changed, e.g. between session value and total value: "123 | 456" or "123 456", ...<br>

- stat tooltips display formatted text instead of plain text<br>

**Internal**<br>

- pause module and show error message to user when the module encounters an unexpected error on session update/reset.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**WARNING: **This version is disabled now because for unknown reasons the tooltips only work in blish 1.1.1 prerelease and not in the official blish release 1.0.0.<br><br>**New**<br>

- session value per hour can be displayed. "/hour" unit text can be changed. This does not affect the stat tooltip.<br>

- separator between values can be changed, e.g. between session value and total value: "123 | 456" or "123 456", ...<br>

- stat tooltips display formatted text instead of plain text<br>

**Internal**<br>

- pause module and show error message to user when the module encounters an unexpected error on session update/reset.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**WARNING: **This version is disabled now because for unknown reasons the tooltips only work in blish 1.1.1 prerelease and not in the official blish release 1.0.0.<br><br>**New**<br>

- session value per hour can be displayed. "/hour" unit text can be changed. This does not affect the stat tooltip.<br>

- separator between values can be changed, e.g. between session value and total value: "123 | 456" or "123 456", ...<br>

- stat tooltips display formatted text instead of plain text<br>

**Internal**<br>

- pause module and show error message to user when the module encounters an unexpected error on session update/reset.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**WARNING: **This version is disabled now because for unknown reasons the tooltips only work in blish 1.1.1 prerelease and not in the official blish release 1.0.0. There will be a new release soon for blish 1.1.1.<br><br>**New**<br>

- session value per hour can be displayed. "/hour" unit text can be changed. This does not affect the stat tooltip.<br>

- separator between values can be changed, e.g. between session value and total value: "123 | 456" or "123 456", ...<br>

- stat tooltips display formatted text instead of plain text<br>

**Internal**<br>

- pause module and show error message to user when the module encounters an unexpected error on session update/reset.<br>

**Pull request merged**
