### PR TITLE
Quick Surrender Release v0.2.5

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/8eb121a7ce22c29192b0f1e365f52de22d98b335..9413df69c60d516d371bc015c3cdd3f6be182803)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.quick_surrender_module_v0.2.5/Nekres.Quick_Surrender_Module-0.2.5.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Quick_Surrender_Module` == `Nekres.Quick_Surrender_Module`? |
| ✔️ | Manifest and package version match. | `0.2.5` == `0.2.5`? |
| ✔️ | Module and package checksum match. | `42A43FC1E7734FF843246023E61CD2F1B3643FFC9FA32B3AC7BE0BA440454DC2` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added**&nbsp;translations for German, French, Spanish.

- **Added**&nbsp;more chat display options.

- **Added** chat message binding for users who have changed their in-game chat binding away from the default [Enter].


### Bugfixes
- **Fixed**&nbsp;random targeting when using the surrender shortcut.

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added**&nbsp;translations for German, French, Spanish.

- **Added**&nbsp;more chat display options.

- **Added** chat message binding for users who have changed their in-game chat binding away from the default [Enter].


### Bugfixes
- **Fixed**&nbsp;random targeting when using the surrender shortcut.

- **Fixed** occasional dodging of the character when chat focus failed.



### Changes
- **Improved** speed of chat command processing using the latest advancements in automated chat technology!

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added**&nbsp;translations for German, French, Spanish.

- **Added**&nbsp;more chat display options.

- **Added** chat message binding for users who have changed their in-game chat binding away from the default [Enter].


### Bugfixes
- **Fixed**&nbsp;random targeting when using the surrender shortcut.

- **Fixed** occasional dodging of the character when chat focus failed.



### Changes
- **Improved** speed and stability of chat command processing using the latest advancements in automated chat technology!

**Pull request merged**
