### PR TITLE
Session Tracker Release v5.0.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Ecksofa

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/b539bf4282219356f30b0dbe7384d8fca0ee3c2c..e420e55e08bfa96579c42007756aef0f4aaf6ea0)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/ecksofa.sessiontracker_v5.0.0/ecksofa.sessiontracker-5.0.0.bhm |
| ✔️ | Manifest and package namespace match. | `ecksofa.sessiontracker` == `ecksofa.sessiontracker`? |
| ✔️ | Manifest and package version match. | `5.0.0` == `5.0.0`? |
| ✔️ | Module and package checksum match. | `FA23D2704C559FD739951E7E34C43960F03C58CCCC1E3706D832AFC880B69742` |

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**Hint** <br>

- new item stats have been added via the backend blish server: trick-or-treat bag, piece of candy corn, mystic coin, fractal encryption<br>

- obsolete currencies have been removed via the backend blish server: old dungeon currencies, red prophet shard/crystal, gaeting crystal<br>

**New**<br>

- errors are displayed as small hint and not as stat values. API token issues that occur while the module is running are now consistent with those on module startup (less "error: read tooltip", more "Add API key!" etc.)<br>

- add mystic coins and fractal encryptions to show/hide fractal stats button<br>

- add mystic coins to show/hide raid stats button<br>

**Internal**<br>

- debug log all setting changes<br>

- add new item stats to model file creator: trick or treat bag, piece of candy corn, mystic coin, fractal encryption<br>

- remove obsolete currencies from model file creator: old dungeon currencies, red prophet shard/crystal, gaeting crystal<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**Hint** <br>

- new item stats have been added via the backend blish server: trick-or-treat bag, piece of candy corn, mystic coin, fractal encryption<br>

- obsolete currencies have been removed via the backend blish server: old dungeon currencies, red prophet shard/crystal, gaeting crystal<br>

**New**<br>

- errors are displayed as small hint and not as stat values. Displaying API token issues that occur while the module is running is now consistent with how they are displayed on module startup (less "error: read tooltip", more "Add API key!" etc.)<br>

- add mystic coins and fractal encryptions to show/hide fractal stats button<br>

- add mystic coins to show/hide raid stats button<br>

**Internal**<br>

- debug log all setting changes<br>

- add new item stats to model file creator: trick or treat bag, piece of candy corn, mystic coin, fractal encryption<br>

- remove obsolete currencies from model file creator: old dungeon currencies, red prophet shard/crystal, gaeting crystal<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
WARNING: release is hidden until a bug with the fixed height setting is fixed that crashes the module. Until then, clear the module settings and do not use fixed height or use version 3.<br><br>

**Hint** <br>

- new item stats have been added via the backend blish server: trick-or-treat bag, piece of candy corn, mystic coin, fractal encryption<br>

- obsolete currencies have been removed via the backend blish server: old dungeon currencies, red prophet shard/crystal, gaeting crystal<br>

**New**<br>

- errors are displayed as small hint and not as stat values. Displaying API token issues that occur while the module is running is now consistent with how they are displayed on module startup (less "error: read tooltip", more "Add API key!" etc.)<br>

- add mystic coins and fractal encryptions to show/hide fractal stats button<br>

- add mystic coins to show/hide raid stats button<br>

**Internal**<br>

- debug log all setting changes<br>

- add new item stats to model file creator: trick or treat bag, piece of candy corn, mystic coin, fractal encryption<br>

- remove obsolete currencies from model file creator: old dungeon currencies, red prophet shard/crystal, gaeting crystal<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
WARNING: release is hidden because a bug with the fixed height setting crashes the module. This is fixed in the upcoming release version 6.<br><br>

**Hint** <br>

- new item stats have been added via the backend blish server: trick-or-treat bag, piece of candy corn, mystic coin, fractal encryption<br>

- obsolete currencies have been removed via the backend blish server: old dungeon currencies, red prophet shard/crystal, gaeting crystal<br>

**New**<br>

- errors are displayed as small hint and not as stat values. Displaying API token issues that occur while the module is running is now consistent with how they are displayed on module startup (less "error: read tooltip", more "Add API key!" etc.)<br>

- add mystic coins and fractal encryptions to show/hide fractal stats button<br>

- add mystic coins to show/hide raid stats button<br>

**Internal**<br>

- debug log all setting changes<br>

- add new item stats to model file creator: trick or treat bag, piece of candy corn, mystic coin, fractal encryption<br>

- remove obsolete currencies from model file creator: old dungeon currencies, red prophet shard/crystal, gaeting crystal<br>

**Pull request merged**
