### PR TITLE
Loading Screen Hints Release v1.1.2

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/2c90c22f00a5a66ab335f5d4e647a4e0d7951116..b14825085018180692f35e12fcd0c67bd59fc6f9)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/bh.general.loadingscreenhints_v1.1.2/bh.general.loadingscreenhints-1.1.2.bhm |
| ✔️ | Manifest and package namespace match. | `bh.general.loadingscreenhints` == `bh.general.loadingscreenhints`? |
| ✔️ | Manifest and package version match. | `1.1.2` == `1.1.2`? |
| ✔️ | Module and package checksum match. | `332EF79580F544C130B7C8C58CE45B06FE911DFB6E1A8A68B2B25E97922E723E` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** webhosted loading screen hints. New hints appear without a module update.

- **Added**&nbsp;support for module specific hints which are hints that appear for *enabled* modules. Module developers can add hints for their modules. Simply forward me your module's namespace (or the root path) and a text you wanna have displayed.

- **Added** localization support for German, French, Spanish. If you run BlishHUD in another language than english you may not get any hints. It is an on-going process to add hints to each language.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** webhosted loading screen hints. New hints appear without a module update.

- **Added**&nbsp;support for module specific hints which are hints that appear for *enabled* modules. Module developers can add hints for their modules. Simply forward me your module's namespace (or the root path if you want that hint to be shown for multiple modules) and a text you wanna have displayed.

- **Added** localization support for German, French, Spanish. If you run BlishHUD in another language than english you may not get any hints. It is an on-going process to add hints to each language.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** webhosted loading screen hints. New hints appear without a module update.

- **Added**&nbsp;support for module specific hints which are hints that appear for *enabled* modules. Module developers can add hints for their modules. Simply forward me your module's namespace (or the root path if you want that hint to be shown for multiple modules) and a text you wanna have displayed.

- **Added** localization support for German, French, Spanish. If you run BlishHUD in another language than english you may not get any hints. It is an on-going process to add hints to each language.


### Changes
- You can now use either mouse button to hide a hint quickly. Click again on its location to show it again.

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
