### PR TITLE
Mount Music Release v1.1.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/3865622e65296e87265fae8b7bda8fa1499455a5..95558acc2d5c2c5bed8d78a9455622c3254a128e)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.music_mixer_v1.1.0/Nekres.Music_Mixer-1.1.0.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Music_Mixer` == `Nekres.Music_Mixer`? |
| ✔️ | Manifest and package version match. | `1.1.0` == `1.1.0`? |
| ✔️ | Module and package checksum match. | `4D16E1C4E3EA1E4BA43BB6EBD609A26B085C4F4094E893D26FFCBA1F0F26742E` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

• Added toggles to playlist dialogs.<br>

• Added backup and revert functionality of ``../Documents/Guild Wars 2/Music/Defeated.m3u`` when toggling the Defeated playlist.<br>

• Removed toggle settings from module settings.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

• Added toggles to playlist dialogs.<br>

• Added backup and revert functionality for ``../Documents/Guild Wars 2/Music/Defeated.m3u`` when toggling the Defeated playlist.<br>

• Removed toggle settings from module settings.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

• Added toggles to playlist dialogs.<br>

• Added backup and revert functionality for ``../Documents/Guild Wars 2/Music/Defeated.m3u`` when toggling the Defeated playlist.<br><br>

• Removed toggle settings from module settings.<br>

• Changed Mount music to just play in maps of type public (open world PvE) and guild halls.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

• Added toggles to playlist dialogs.<br>

• Added backup and revert functionality for ``../Documents/Guild Wars 2/Music/Defeated.m3u`` when toggling the Defeated playlist.<br><br>

• Removed toggle settings from module settings.<br>

• Changed Mount music to just play in maps of type public (open world, cities) and guild halls.<br>

**Pull request merged**
