### PR TITLE
Screenshot Manager Release v0.5.2

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/855d41f2c4e053474557b6670acef28fde77c0a5..8fa33558641c16a8fc1735a9b0c3bf41b9a6741b)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.screenshot_manager_v0.5.2/Nekres.Screenshot_Manager-0.5.2.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Screenshot_Manager` == `Nekres.Screenshot_Manager`? |
| ✔️ | Manifest and package version match. | `0.5.2` == `0.5.2`? |
| ✔️ | Module and package checksum match. | `19F6E264082AD237C9A5196C27479175F879DE55D8659E1A247E0FB59AE3FDB9` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- Fixed saving screenshots on network share (eg. OneDrive).<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- **Fixed** saving screenshots on network share (eg. OneDrive).<br>

**Comment by agaertner** [comment]
I remembered an issue reported by a user of another module (Stream Out) when saving images to a cloud folder (eg. OneDrive) and didn't apply it here initially.

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Hotfix
- **Fixed** saving screenshots on network share (eg. OneDrive).

**Pull request merged**
