### PR TITLE
Event Table Release v3.13.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Estreya

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/b53e6e1ed93ecba9cfd0dc2a21aa76d9d5669f1d..ee181c8329f36c377d70e48297830e862df116ad)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/estreya.bh.eventtable_v3.13.0/estreya.bh.eventTable-3.13.0.bhm |
| ✔️ | Manifest and package namespace match. | `estreya.bh.eventTable` == `estreya.bh.eventTable`? |
| ✔️ | Manifest and package version match. | `3.13.0` == `3.13.0`? |
| ✔️ | Module and package checksum match. | `9C67D420AC5C17E07C9A1E730F887E58C07D0FF197E810F44FDC80C75E12354A` |

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Features**<br>

- Added&nbsp;automatic pasting of event waypoints to the ingame chat.
Supports all chats and is configurable in different chat formats (more text vs. just waypoint)
Is divided into settings per event area and settings for reminders


**** BREAKING CHANGES FOR CONTEXT ****<br>

The AddEvent struct has the following changes:<br>

- Removed property "Location"

- Added property "Locations". The locations struct property "Tooltip" has the same functionality as the previous property "Location"


**Info for WINE users**<br>

The usage of the module on WINE as provided via the normal blish repo causes blish to crash.<br>The reason for that is the usage of the windows foundation universal api contract for OS notifications which is not fully implemented in WINE.<br>If you want to use the module on WINE please join my discord and give me a ping so I can provide you a build without this feature. You CAN'T use the update feature for modules when using that custom build.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Features**<br>

- Added&nbsp;automatic pasting of event waypoints to the ingame chat.
Supports all chats and is configurable in different chat formats (more text vs. just waypoint)
Is divided into settings per event area and settings for reminders


**** BREAKING CHANGES FOR CONTEXT ****<br>

The AddEvent struct has the following changes:<br>

- Removed property "Location"

- Added property "Locations". The locations struct property "Tooltip" has the same functionality as the previous property "Location"


**Info for WINE users**<br>

The usage of the module on WINE as provided via the normal blish repo causes blish to crash.<br>The reason for that is the usage of the windows foundation universal api contract for OS notifications which is not fully implemented in WINE.<br>If you want to use the module on WINE please join my discord and give me a ping so I can provide you a build without this feature. <br><br>*You CAN'T use the update feature for modules when using that custom build.*<br>

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Features**<br>

- Added&nbsp;automatic pasting of event waypoints to the ingame chat.
Supports all chats and is configurable in different chat formats (more text vs. just waypoint)
Is divided into settings per event area and settings for reminders


**BREAKING CHANGES FOR CONTEXT**<br>

The AddEvent struct has the following changes:<br>

- Removed property "Location"

- Added property "Locations". The locations struct property "Tooltip" has the same functionality as the previous property "Location"


**Info for WINE users**<br>

The usage of the module on WINE as provided via the normal blish repo causes blish to crash.<br>The reason for that is the usage of the windows foundation universal api contract for OS notifications which is not fully implemented in WINE.<br>If you want to use the module on WINE please join my discord and give me a ping so I can provide you a build without this feature. <br><br>*You CAN'T use the update feature for modules when using that custom build.*<br>

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
