### PR TITLE
Regions of Tyria Release v0.12.5

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/28b2524446f101b1650c33d7c3af7280c27f3922..56aa980bd9035746fa8ebd39f417b93db0f657bb)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.regions_of_tyria_v0.12.5/Nekres.Regions_Of_Tyria-0.12.5.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Regions_Of_Tyria` == `Nekres.Regions_Of_Tyria`? |
| ✔️ | Manifest and package version match. | `0.12.5` == `0.12.5`? |
| ✔️ | Module and package checksum match. | `52C15784B47A6F2412237066D4E90259E5BAD210F45DEDBFBBBE18DD59F47B0D` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Bugfixes
- Discard preceding or trailing generic info like "Strike Mission:"  or "(Public)" as they often lead to overlong zone names and are not part of the actual name.

- Make header the main name where the API still just has a placeholder such as "((1089116))".

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Changes
- Discard preceding or trailing generic info like "Strike Mission:"  or "(Public)" as they often lead to overlong zone names and are not part of the actual name.

- Make header the main name where the API still just has a placeholder such as "((1089116))".

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Changes
- Discard preceding or trailing generic info like "Strike Mission:"  or "(Public)" as they often lead to overlong zone names and are not part of the actual name.

- Make header the main name where the API just provides a placeholder such as "((1089116))".

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Changes
- Discard preceding or trailing generic info like "Strike Mission:"  or "(Public)" as they often lead to overlong zone names and are not part of the actual name.

- Make header the main name where the API just provides a placeholder value such as "((1089116))".

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
