### PR TITLE
Proof Logix Release v2.21.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/fb8f4eed5e15beb5954b784d73b51c6573000a07..08b4a5b8a768712ea6e73c5e04993e79d94460d0)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/killproofmodule_v2.21.0/KillProofModule-2.21.0.bhm |
| ✔️ | Manifest and package namespace match. | `KillProofModule` == `KillProofModule`? |
| ✔️ | Manifest and package version match. | `2.21.0` == `2.21.0`? |
| ✔️ | Module and package checksum match. | `4393803C7AF93A604151FCB481D041F7338EAF3EC286841A809DA437FB563220` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

• Added Online Status column to Party Table.<br>

• Added "Keep Leavers" to Party Table settings.<br>

• Added "Always Sort by Status" to Party Table settings.<br>

• Reduce margin of Party Table columns to be more compact.<br>

• Fixed Profile windows not disposing on module unload.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

• Added Online Status column to Party Table.<br>

• Added "Keep Leavers" to Party Table settings.<br>

• Added "Always Sort by Status" to Party Table settings.<br>

• Reduced margin of Party Table columns to be more compact.<br>

• Fixed Profile windows not disposing on module unload.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

• Added Online Status column to Party Table.<br>

• Added "Keep Leavers" to Party Table settings.<br>

• Added "Always Sort by Status" to Party Table settings.<br>

• Reduced margins of Party Table columns to be more compact.<br>

• Fixed Profile windows not disposing on module unload.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- &nbsp;**Added** Online Status column to Party Table.

- **Added** "Always Sort by Status" to Party Table settings.


- **Added** "Keep Leavers" to Party Table settings.



### Changes
- **Reduced** margins of Party Table columns to be more compact.


### Bugfixes
- **Fixed** Profile windows not disposing on module unload.

**Pull request merged**
