### PR TITLE
Proof Logix Release v2.22.9

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/487c6caf18760ce9c085c28e025926c58f66ccdc..f1d105ba031527aa59d36391e93524ad00c6d9d9)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/killproofmodule_v2.22.9/KillProofModule-2.22.9.bhm |
| ✔️ | Manifest and package namespace match. | `KillProofModule` == `KillProofModule`? |
| ✔️ | Manifest and package version match. | `2.22.9` == `2.22.9`? |
| ✔️ | Module and package checksum match. | `E1109314651396E24E1E6E081F6A3CA780087332D4FE292198F3F6E40D04D2CD` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Bugfix
- **Fixed** "API disabled" message.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Bugfix
- **Fixed** "API disabled" message. (+ refactoring)

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Bugfix
- **Fixed** "API disabled" message.

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
