### PR TITLE
Regions of Tyria Release v0.6.19

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/33d5aee703ad4c7435a2a8975c84cf97b95c668c..ac1ffd882727f5f2f434165679a90eb14bd5b42f)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.regions_of_tyria_v0.6.19/Nekres.Regions_Of_Tyria-0.6.19.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Regions_Of_Tyria` == `Nekres.Regions_Of_Tyria`? |
| ✔️ | Manifest and package version match. | `0.6.19` == `0.6.19`? |
| ✔️ | Module and package checksum match. | `3410865D98FF97C0D554452232492205C72E02F2217CB4564B4A0C4603640832` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

• **Fixed** crash when trying to request info of a map missing on the web API.<br>

• **Changed** settings formatting.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br><br>• **Fixed** competitive modes using camera position instead of avatar position for area detection since the later was previously disabled.<br><br>

• **Fixed** crash when trying to request info of a map missing on the web API.<br>

• **Changed** settings formatting.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**&nbsp;&nbsp;<br><br>• **Fixed** competitive modes using camera position instead of avatar position for area detection since the later was previously disabled.<br><br>

• **Fixed** crash when trying to request info of a map missing on the web API.<br>

• **Changed** settings formatting.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**&nbsp;&nbsp;<br>

<br>• **Fixed** competitive modes using camera position instead of avatar position for area detection since the later was previously disabled.<br><br>

• **Fixed** crash when trying to request info of a map missing on the web API.<br>

• **Changed** settings formatting.<br>

**Pull request merged**
