### PR TITLE
Stream Out Release v0.9.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/87244373b68c2eea684397953a5289317a686e1b..352b2578bd9c982a613da38f08ed06430f778003)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.stream_out_v0.9.1/Nekres.Stream_Out-0.9.1.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Stream_Out` == `Nekres.Stream_Out`? |
| ✔️ | Manifest and package version match. | `0.9.1` == `0.9.1`? |
| ✔️ | Module and package checksum match. | `D859DA9E84BAE90FE5860B6EDA1C2742DFF02E0C9FDE7ADA5D523BDB3DF7B77D` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- **Fixed** ``no such id`` crash on new maps not existing on the web API.<br>

- **Added** ``combat.txt`` and ``combat_icon.png`` indicating if you are in combat.<br>

- **Removed** ``deaths_wvw.txt``<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- **Fixed** ``no such id`` crash on new maps not existing on the web API.<br>

- **Added** ``combat.txt`` and ``combat_icon.png`` indicating if you are in combat.<br>

- **Removed** ``deaths_wvw.txt`` (use ``deaths_weekly.txt`` instead)<br>

- **Replaced** global reset check with reset check (last/next reset timestamp) for each export service which allows individual export services to retry if a reset fails due to API requests failing.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- **Fixed** ``no such id`` crash on new maps not existing on the web API.<br>

- **Added** ``combat.txt`` and ``combat_icon.png`` indicating if you are in combat.<br>

- **Removed** ``deaths_wvw.txt`` (use ``deaths_weekly.txt`` instead)<br>

- **Replaced** global reset check with individual reset checks per export service allowing single services to retry alone when a reset fails.<br>

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
