### PR TITLE
Proof Logix Release v2.18.5

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/be01be69f38bae38cc0c9cf25e0dc5533d45c350..8f15bc9ea15791aac4ac3b699e4c95bcd8f93940)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/killproofmodule_v2.18.5/KillProofModule-2.18.5.bhm |
| ✔️ | Manifest and package namespace match. | `KillProofModule` == `KillProofModule`? |
| ✔️ | Manifest and package version match. | `2.18.5` == `2.18.5`? |
| ✔️ | Module and package checksum match. | `1689FCC2515FC7CAA3B1EAE49277AB08897F3AEFB8246403811AE094A7C2408C` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

•  Fixed slow loading of initial module startup.<br>

•  Fixed wings with no token records displaying in Smart Ping menu.<br>

•  Fixed coffers being wrongly placed under general tokens in context menus.<br>

•  Fixed wiki hyperlinks for encounters not respecting the overlay language.<br>

•  Removed brackets from items in Profiles.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

•  Fixed slow loading of initial module startup.<br>

•  Fixed wings with no token records displaying in Smart Ping menu.<br>

•  Fixed coffers being wrongly placed under general tokens in context menus.<br>

• Fixed scrollbars overlaying panels in all Clears panels.<br>

•  Fixed wiki hyperlinks for encounters not respecting the overlay language.<br>

•  Removed brackets from items in Profiles.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

•  Fixed slow loading of initial module startup.<br>

•  Fixed wings with no token records displaying in Smart Ping menu.<br>

•  Fixed coffers being wrongly placed under general tokens in context menus.<br>

• Fixed panel title bars clipping into the scrollbar area in Weekly Clears panels.<br>

•  Fixed wiki hyperlinks for encounters not respecting the overlay language.<br>

•  Removed brackets from items in Profiles.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

•  Fixed slow loading of initial module startup.<br>

•  Fixed wings with no token records displaying in Smart Ping menu.<br>

•  Fixed coffers being wrongly placed under general tokens in context menus.<br>

• Fixed panel titlebars clipping into the scrollbar area in Weekly Clears panels.<br>

•  Fixed wiki hyperlinks for encounters not respecting the overlay language.<br>

•  Removed brackets from items in Profiles.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Changes
- **Removed** brackets from items in Profiles.


### Bugfixes
- **Fixed** slow loading of initial module startup.

- **Fixed** wings with no token records displaying in Smart Ping menu.


- **Fixed** coffers being wrongly placed under general tokens in context menus.


- **Fixed** panel titlebars clipping into the scrollbar area in Weekly Clears panels.


- **Fixed** wiki hyperlinks for encounters not respecting the overlay language.

**Pull request merged**
