### PR TITLE
GW2 Window Resizer Release v0.2.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/7f195c9282a7ba58494d56642e0737bfe3aba53f..4ec1ddba6b9552af0e74f6f37aef5cac3f464559)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.windowresize_v0.2.1/Nekres.WindowResize-0.2.1.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.WindowResize` == `Nekres.WindowResize`? |
| ✔️ | Manifest and package version match. | `0.2.1` == `0.2.1`? |
| ✔️ | Module and package checksum match. | `A6767A26924E5A07C98B261C9A0E2913A2F4EE3663968C16F84F9C0112A04DB5` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### GW2 Window Resize
Resizes the GW2 window to a preferred size when you are switching to windowed mode.<br>

The window size of GW2 doesn't automatically switch to a preferred size when switching from windowed fullscreen to windowed mode and often overwrites the set size. This module will fix that.<br><br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### GW2 Window Resize
Resizes the GW2 window to a preferred size when you are switching to windowed mode.<br>

The window size of GW2 doesn't automatically switch to a preferred size when switching from windowed fullscreen to windowed mode and often overwrites the preferred size. This module will fix that.<br><br>

If you ever wanted to stream to your friends in 16:9 but your screen is 420x69 too large to do that efficiently this module is for you.<br><br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
Resizes the GW2 window to a preferred size when you are switching to windowed mode.<br>

The window size of GW2 doesn't automatically switch to a preferred size when switching from windowed fullscreen to windowed mode and often overwrites the preferred size. This module will fix that.<br><br>

If you ever wanted to stream to your friends in 16:9 but your screen is 420x69 too large to do that efficiently this module is for you.<br><br>

**Pull request merged**
