### PR TITLE
Music Mixer Release v0.9.15

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/61581fbff40e0278591508d672e3bb8c07802104..a426ab83925b3d545960e0c1b66ffecea5621e98)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.music_mixer_v0.9.15/Nekres.Music_Mixer-0.9.15.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Music_Mixer` == `Nekres.Music_Mixer`? |
| ✔️ | Manifest and package version match. | `0.9.15` == `0.9.15`? |
| ✔️ | Module and package checksum match. | `1800FB703CC345A57EB4C4A311DB3DD2AEFA53D8D4284866EED02067CA2D0C5F` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- **Fixed** a crash during loading of maps.<br>

- **Fixed** intermediate songs not fading out (eg. when dismounting).<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- **Fixed** a crash during loading of maps.<br>

- **Fixed** intermediate songs not fading out (eg. when dismounting).<br>

- **Fixed** youtube links not working as of a recent youtube update.<br>

*Technical: Swapping youtube-dl with yt-dlp may have resulted in faster load times as well.*<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- **Updated** BlishHUD dependency to &gt;=1.0.0<br>

- **Fixed** a crash during loading of maps for the interface.<br>

- **Fixed** intermediate songs not fading out (eg. when dismounting).<br>

- **Fixed** youtube links not working as of a recent youtube update.<br>

*Technical: Swapped youtube-dl with yt-dlp.*<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release deleted by Nekres.  PR will be closed.

**Comment by agaertner** [comment]
Closed due to oversight: yt-dlp dependency was missing in repo due to being .gitignore'd. Fixed in #505

**Pull request closed without merging**
