### PR TITLE
Builds Manager Release v1.0.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Kenedia

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/2502c56a982a4fa5fb6f60e8d6cb87f6b6e91a95..3cecef5068a605c080ffd27e9f50f0f942badc32)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/kenedia.modules.buildsmanager_v1.0.0/Kenedia.Modules.BuildsManager-1.0.0.bhm |
| ✔️ | Manifest and package namespace match. | `Kenedia.Modules.BuildsManager` == `Kenedia.Modules.BuildsManager`? |
| ✔️ | Manifest and package version match. | `1.0.0` == `1.0.0`? |
| ✔️ | Module and package checksum match. | `A8B9932566C65CA3397E46E9A9F7C2DFC6BA72EF89202592E58EAE85400EC66F` |

**Comment by BlishHUD** [comment]
Release notes updated by Kenedia.<br><br>
**Initial Release**<br>

**Comment by BlishHUD** [comment]
Release notes updated by Kenedia.<br><br>
### Initial Release

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release deleted by Kenedia.  PR will be closed.

**Comment by BlishHUD** [comment]
Release deleted by Kenedia.  PR will be closed.

**Pull request closed without merging**
