### PR TITLE
Farming Tracker Release v2.0.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Ecksofa

### CODE REVIEW

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
Requires Blish HUD 1.1.1 from https://blishhud.com/ <br>

**New**<br>

- profit window: new setting to show a permanent profit window. The profit window is even visible when the farming tracker window is hidden.<br>

- new settings to adjust profit label texts (e.g. change "Profit per hour" to "/h")<br>

- export csv: new button to export tracking summary as CSV. CSV format is the same as on the drf live tracker website. CSV File is saved to 'Documents\Guild Wars 2\addons\blishhud\farming-tracker\&lt;date_time&gt;.csv'.<br>

- updated DRF setup instruction and troubleshooting regarding the "Connected" status. And improved text wrapping by using automatic wrapping.<br>

**Fixed**<br>

- tab icon texture was not disposed<br>

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/7f195c9282a7ba58494d56642e0737bfe3aba53f..e1acdb0c815826261015cd81c3cb7fa14845b857)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/ecksofa.farmingtracker_v2.0.0/ecksofa.farmingtracker-2.0.0.bhm |
| ✔️ | Manifest and package namespace match. | `ecksofa.farmingtracker` == `ecksofa.farmingtracker`? |
| ✔️ | Manifest and package version match. | `2.0.0` == `2.0.0`? |
| ✔️ | Module and package checksum match. | `C2075E4AC964FDD43B460861ACD19A69BA7703311C15D15A7BF1AED7707805B5` |

**Comment by BlishHUD** [comment]
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/ecksofa.farmingtracker_v2.0.0/ecksofa.farmingtracker-2.0.0.bhm |
| ✔️ | Manifest and package namespace match. | `ecksofa.farmingtracker` == `ecksofa.farmingtracker`? |
| ✔️ | Manifest and package version match. | `2.0.0` == `2.0.0`? |
| ✔️ | Module and package checksum match. | `C2075E4AC964FDD43B460861ACD19A69BA7703311C15D15A7BF1AED7707805B5` |

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
Requires Blish HUD 1.1.1 from https://blishhud.com/. Older Blish versions will NOT offer a self update to Blish 1.1.1 at the moment. You have to manually download Blish 1.1.1 from the website.<br>

**New**<br>

- profit window: new setting to show a permanent profit window. The profit window is even visible when the farming tracker window is hidden.<br>

- new settings to adjust profit label texts (e.g. change "Profit per hour" to "/h")<br>

- export csv: new button to export tracking summary as CSV. CSV format is the same as on the drf live tracker website. CSV File is saved to 'Documents\Guild Wars 2\addons\blishhud\farming-tracker\&lt;date_time&gt;.csv'.<br>

- updated DRF setup instruction and troubleshooting regarding the "Connected" status. And improved text wrapping by using automatic wrapping.<br>

**Fixed**<br>

- tab icon texture was not disposed<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**New**<br>

- profit window: new setting to show a permanent profit window. The profit window is even visible when the farming tracker window is hidden.<br>

- new settings to adjust profit label texts (e.g. change "Profit per hour" to "/h")<br>

- export csv: new button to export tracking summary as CSV. CSV format is the same as on the drf live tracker website. CSV File is saved to 'Documents\Guild Wars 2\addons\blishhud\farming-tracker\&lt;date_time&gt;.csv'.<br>

- updated DRF setup instruction and troubleshooting regarding the "Connected" status. And improved text wrapping by using automatic wrapping.<br>

**Fixed**<br>

- tab icon texture was not disposed<br>

**Pull request merged**
