### PR TITLE
Achievement Tracker Release v0.1.3

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Denrage

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/894d5508fd833b91af5f0cd9b8be57fe9ff5075b..7cec42644e62027c270b1f1bd14a396d33f3fc4f)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/denrage.achievementtrackermodule_v0.1.3/Denrage.AchievementTrackerModule-0.1.3.bhm |
| ✔️ | Manifest and package namespace match. | `Denrage.AchievementTrackerModule` == `Denrage.AchievementTrackerModule`? |
| ✔️ | Manifest and package version match. | `0.1.3` == `0.1.3`? |
| ✔️ | Module and package checksum match. | `A5D9267CA63992A47839F87AA3D157430C215F5E7F8FA18B65D5C6E38C31D7F2` |

**Comment by BlishHUD** [comment]
Release notes updated by Denrage.<br><br>
In this version i give the people who wanna live dangerously and are killing blisshud to let them save all perstistant information every 5 minutes. This will do a save regardless if smth changed, so use it wisely or just close blishhud how it is supposed to be.<br>

I got multiple mentions about bugs, weird behaviour or usage problems with an absurd amount of tracked achievements, therefor i will limit the maximum tracked achievements to 15. This can be disabled in settings but keep in mind that anything above that can get performance hits, increased memory usage, increased disk usage, display and usage bugs and the problem to use the list at all. Try to complete some achievements before removing the limit :D<br>

There is also finally the trading post prices of items included \o/<br>

For all of those that dont want to wait for the api to update, you can mark steps as completed with a right click. This will only overwrite the api information in the complete state, you cant (un)mark achievements that are completed in the api.<br>

And lastly i made the whole tracker a little bit more responsive and it wont hang till it created all the controls.<br>

Fixed opening wrong subpage with only a part of the name (Sunrise f.e.)<br>

Dont block ui for creating any controls- Fixed wrong completion state for Tide Turner (DRM) Achievements<br>

Added an option to save every persistant information every 5 minutes<br>

Added a max cap of 15 tracked achievements (can be disabled in the module settings)<br>

Added up to date trading post prices for items<br>

Added the possibility to mark a step in an achievement as completed with right click

<br>

**Comment by BlishHUD** [comment]
Release notes updated by Denrage.<br><br>
In this version i give the people who wanna live dangerously and are killing blisshud to let them save all perstistant information every 5 minutes. This will do a save regardless if smth changed, so use it wisely or just close blishhud how it is supposed to be.<br>

I got multiple mentions about bugs, weird behaviour or usage problems with an absurd amount of tracked achievements, therefor i will limit the maximum tracked achievements to 15. This can be disabled in settings but keep in mind that anything above that can get performance hits, increased memory usage, increased disk usage, display and usage bugs and the problem to use the list at all. Try to complete some achievements before removing the limit :D<br>

There is also finally the trading post prices of items included \o/<br>

For all of those that dont want to wait for the api to update, you can mark steps as completed with a right click. This will only overwrite the api information in the complete state, you cant (un)mark achievements that are completed in the api.<br>

And lastly i made the whole tracker a little bit more responsive and it wont hang till it created all the controls.<br>

Changelog:<br>

- Fixed opening wrong subpage with only a part of the name (Sunrise f.e.)<br>

- Dont block ui for creating any controls- Fixed wrong completion state for Tide Turner (DRM) Achievements<br>

- Added an option to save every persistant information every 5 minutes<br>

- Added a max cap of 15 tracked achievements (can be disabled in the module settings)<br>

- Added up to date trading post prices for items<br>

- Added the possibility to mark a step in an achievement as completed with right click

<br>

**Comment by BlishHUD** [comment]
Release notes updated by Denrage.<br><br>
In this version i give the people who wanna live dangerously and are killing blisshud to let them save all perstistant information every 5 minutes. This will do a save regardless if smth changed, so use it wisely or just close blishhud how it is supposed to be.<br>

I got multiple mentions about bugs, weird behaviour or usage problems with an absurd amount of tracked achievements, therefor i will limit the maximum tracked achievements to 15. This can be disabled in settings but keep in mind that anything above that can get performance hits, increased memory usage, increased disk usage, display and usage bugs and the problem to use the list at all. Try to complete some achievements before removing the limit :D<br>

There is also finally the trading post prices of items included \o/<br>

For all of those that dont want to wait for the api to update, you can mark steps as completed with a right click. This will only overwrite the api information in the complete state, you cant (un)mark achievements that are completed in the api.<br>

And lastly i made the whole tracker a little bit more responsive and it wont hang till it created all the controls.<br>

Changelog:<br>

- Fixed opening wrong subpage with only a part of the name (Sunrise f.e.)<br>

- Dont block ui for creating any controls<br>

- Fixed wrong completion state for Tide Turner (DRM) Achievements<br>

- Added an option to save every persistant information every 5 minutes<br>

- Added a max cap of 15 tracked achievements (can be disabled in the module settings)<br>

- Added up to date trading post prices for items<br>

- Added the possibility to mark a step in an achievement as completed with right click

<br>

**Comment by BlishHUD** [comment]
Release notes updated by Denrage.<br><br>
In this version i give the people who wanna live dangerously and are killing blisshud to let them save all perstistant information every 5 minutes. This will do a save regardless if smth changed, so use it wisely or just close blishhud how it is supposed to be.<br>

I got multiple mentions about bugs, weird behaviour or usage problems with an absurd amount of tracked achievements, therefor i will limit the maximum tracked achievements to 15. This can be disabled in settings but keep in mind that anything above that can get performance hits, increased memory usage, increased disk usage, display and usage bugs and the problem to use the list at all. Try to complete some achievements before removing the limit :D<br>

There is also finally the trading post prices of items included \o/<br>

For all of those that dont want to wait for the api to update, you can mark steps as completed with a right click. This will only overwrite the api information in the complete state, you cant (un)mark achievements that are completed in the api.<br>

And lastly i made the whole tracker a little bit more responsive and it wont hang till it created all the controls.<br>

Changelog:<br>

- Fixed opening wrong subpage with only a part of the name (Sunrise f.e.)<br>

- Dont block ui for creating any controls<br>

- Fixed wrong completion state for Tide Turner (DRM) Achievements<br>

- Added an option to save every persistant information every 5 minutes<br>

- Added a max cap of 15 tracked achievements (can be disabled in the module settings)<br>

- Added up to date trading post prices for items<br>

- Added the possibility to mark a step in an achievement as completed with right click

<br>

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
