### PR TITLE
Regions of Tyria Release v0.8.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/512a44cc99c934846b0cab4eca719345d21854e2..56d3d0fb85544f72c8793adf1dbe9f6048768b92)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.regions_of_tyria_v0.8.1/Nekres.Regions_Of_Tyria-0.8.1.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Regions_Of_Tyria` == `Nekres.Regions_Of_Tyria`? |
| ✔️ | Manifest and package version match. | `0.8.1` == `0.8.1`? |
| ✔️ | Module and package checksum match. | `8C2C26CC8A2FDE82345D574C28FE14AC73E3866904BF3D0B5E43AB4FED0EAB65` |

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Changes
- **Reduced** internal cooldown from 20 to 5 seconds.

- **Unlocked&nbsp;**max**&nbsp;**precision of zone boundaries and player location.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Changes
- **Reduced** internal cooldown from 20 to 5 seconds.

- **Unlocked**&nbsp;max**&nbsp;**precision of zone boundaries and player location.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Changes
- **Reduced** internal cooldown from 20 to 5 seconds.

- **Unlocked** max precision of zone boundaries and player location.

**Pull request merged**
