### PR TITLE
Chat Shorts Release v0.15.11

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/20811f8c5389c10c1584b4281c4f189c3589b428..67b47e6436339b9208b7e5d2fc35da9201150d1a)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.chat_shorts_v0.15.11/Nekres.Chat_Shorts-0.15.11.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Chat_Shorts` == `Nekres.Chat_Shorts`? |
| ✔️ | Manifest and package version match. | `0.15.11` == `0.15.11`? |
| ✔️ | Module and package checksum match. | `58DBD7415BEAA579E1A0F81FE77EDC7167D67809FE858F6E5B1AEC3EB80C5F89` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** {hour} placeholder.

- **Added** {min} placeholder.

- **Fixed** {randon} placeholder returning 0 when called too early.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** {hour} placeholder.

- **Added** {min} placeholder.


### Bugfix
- **Fixed** {randon} placeholder returning 0 when called too early

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** {hour} placeholder.

- **Added** {min} placeholder.


### Bugfix
- **Fixed** {random} placeholder returning 0 when called too early

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** {hour} placeholder.

- **Added** {min} placeholder.


### Bugfix
- **Fixed** {random} placeholder returning 0 when called too early

**Pull request merged**
