### PR TITLE
EmoteTome Release v1.1.2

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Kiroho

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/f415fa2ea67679f02979693c8ab4300a960f8ca8..27b9101df9fea038a63c0117e8f7c34a67accf27)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/kiroho.joka.emotetome_v1.1.2/Kiroho.Joka.EmoteTome-1.1.2.bhm |
| ✔️ | Manifest and package namespace match. | `Kiroho.Joka.EmoteTome` == `Kiroho.Joka.EmoteTome`? |
| ✔️ | Manifest and package version match. | `1.1.2` == `1.1.2`? |
| ✔️ | Module and package checksum match. | `B52884C6066E758A8F01A1345E8442389B1B49517015C11C2A8195420B8409D3` |

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Freesnöw.<br><br>
Adds a priority to the icon.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Kiroho.<br><br>
Added /Unleash Emote<br><br>

**Comment by BlishHUD** [comment]
Release notes updated by Kiroho.<br><br>
Added icon priority<br><br>

**Pull request merged**
