### PR TITLE
Session Tracker Release v2.2.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Ecksofa

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/0ad385e60eb92968557c699aee3d3c5e56931713..fcd73f13a6607d855a5e2df34264798f6d2bbfaf)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/ecksofa.sessiontracker_v2.2.0/ecksofa.sessiontracker-2.2.0.bhm |
| ✔️ | Manifest and package namespace match. | `ecksofa.sessiontracker` == `ecksofa.sessiontracker`? |
| ✔️ | Manifest and package version match. | `2.2.0` == `2.2.0`? |
| ✔️ | Module and package checksum match. | `225C56548A6853105DA3DC91CE86BC760E6CD0618673D9939763F209F241F447` |

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
### New
- added
setting to select when to perform an automatic session reset instead of always
resetting the session on module startup. Options: never, on module startup,
daily reset, weekly reset (regular, wvw, map bonus reward), minutes after
module shutdown. Manual resetting is still possible by clicking reset in the
right click context menu of the menu icon. <br>

- added
hide stats category buttons<br>

### Internal
- current
dateTime can be mocked in hidden debug settings tab to test automatic resets<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
### New
- added setting to select when to perform an automatic session reset instead of always
resetting the session on module startup. Options: never, on module startup,
daily reset, weekly reset (regular, wvw, map bonus reward), minutes after
module shutdown. Manual resetting is still possible by clicking reset in the
right click context menu of the menu icon. <br>

- added
hide stats category buttons<br>

### Internal
- current dateTime can be mocked in hidden debug settings tab to test automatic resets<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
### New
- added setting to select when to perform an automatic session reset instead of always
resetting the session on module startup. Options: never, on module startup,
daily reset, weekly reset (regular, wvw, map bonus reward), minutes after
module shutdown. Manual resetting is still possible by clicking reset in the
right click context menu of the menu icon. <br>

- added hide stats category buttons<br>

### Internal
- current dateTime can be mocked in hidden debug settings tab to test automatic resets<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
### New
- added setting to select when to perform an automatic session reset instead of always resetting the session on module startup. Options: never, on module startup,
daily reset, weekly reset (regular, wvw, map bonus reward), minutes after
module shutdown. Manual resetting is still possible by clicking reset in the
right click context menu of the menu icon. <br>

- added hide stats category buttons<br>

### Internal
- current dateTime can be mocked in hidden debug settings tab to test automatic resets<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
### New
- added setting to select when to perform an automatic session reset instead of always resetting the session on module startup. Options: never, on module startup, daily reset, weekly reset (regular, wvw, map bonus reward), minutes after module shutdown. Manual resetting is still possible by clicking reset in the
right click context menu of the menu icon. <br>

- added hide stats category buttons<br>

### Internal
- current dateTime can be mocked in hidden debug settings tab to test automatic resets<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
### New
- added setting to select when to perform an automatic session reset instead of always resetting the session on module startup. Options: never, on module startup, daily reset, weekly reset (regular, wvw, map bonus reward), minutes after module shutdown. Manual resetting is still possible by clicking reset in the right click context menu of the menu icon. <br>

- added hide stats category buttons<br>

### Internal
- current dateTime can be mocked in hidden debug settings tab to test automatic resets<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**New**<br>

- added setting to select when to perform an automatic session reset instead of always resetting the session on module startup. Options: never, on module startup, daily reset, weekly reset (regular, wvw, map bonus reward), minutes after module shutdown. Manual resetting is still possible by clicking reset in the right click context menu of the menu icon. <br>

- added hide stats category buttons<br>

**Internal**<br>

- current dateTime can be mocked in hidden debug settings tab to test automatic resets<br>

**Pull request merged**
