### PR TITLE
SquadTracker v0.1.2

### PR DESCRIPTION
**Pull request by tcwatson**
Avoids a potential race condition when a player leaves the squad before their `DetailsButton` has been rendered.

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/999d39a2ec127c290aaf5614602a134e5906b3f9..8bf1764520eb6de75cd75b830c60d8f3e2697ab2)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/tcwatson/SquadTracker/releases/download/v0.1.2/SquadTracker.bhm |
| ✔️ | Manifest and package namespace match. | `Torlando.SquadTracker` == `Torlando.SquadTracker`? |
| ✔️ | Manifest and package version match. | `0.1.2` == `0.1.2`? |
| ✔️ | Module and package checksum match. | `EF4874ED6183FD65E865A02B5B430AC3E997E471584466BCB5CA45F29146CD6D` |

**Comment by dlamkins** [comment]
Do we have any guarantees that we're not on the main thread when you call that sleep?  Since it's an event handler call from the ArcDps service, it shouldn't since that's all split out, but event calls based on `RawCombatEvent` (such as PlayerRemoved) do block the socket server (see: https://github.com/blish-hud/Blish-HUD/blob/367d1d59ace65de62e2a421219826d96384ae4e0/Blish%20HUD/GameServices/ArcDpsService.cs#L92) so I suspect some info from the arcdps bridge may get lost due to timeout (or flood us if not within timout) once the processing completes.

In any case, you might try manually testing to confirm that this won't cause Blish HUD to hitch (either the main loop or the socket listener) as a result of the thread.sleep.

https://github.com/dlamkins/bhud-module-src-test/compare/999d39a2ec127c290aaf5614602a134e5906b3f9..8bf1764520eb6de75cd75b830c60d8f3e2697ab2#diff-ccc15ae1f4da0bc9472ae22bf496432a57d847f84dab6a867aefdfba49063a2bR79

**Comment by tcwatson** [comment]
Great question. I'm not so sure that there are any ways to guarantee we wouldn't be on the main thread. For now, the sleep is only on `PlayerRemovedEvent`, but I don't know enough about it to say for certain that it would never block the main thread. 

Is there an alternative way to "wait" before retrying? The main concern here is that, if this race condition were to occur (which _might_ have been what happened in the crash reported shortly after our launch - we were never able to reproduce it, so haven't been able to manually test this unhappy path) and we _didn't_ retry removing it from the Current Squad Members panel, we'd end up with a player being listed as a current squad member in the UI, when in fact they had already left the squad. And with no current way to manually remove players from the squad, there would never be another ArcDPS event that signaled them leaving. 

If there is a way to `await` the rendering (or more accurately, all of the ArcDPS `PlayerAddedEvent`s being processed and the `_playerDisplays` being up to date with all the queued events), I could use that instead of the clumsy thread wait for 3 seconds.

**Comment by dlamkins** [comment]
One idea might be to use the event to queue the action and then in your update loop consume from the queue to add or remove players.  That helps remove any cross-thread shenanigans (especially with UI) since it'll all be on the main thread then.

You could make the event handlers async which I believe would get scheduled outside of the socket listener's thread, but I'd have to refresh myself on how that works.  🤔 

I will think it over some more.

**Pull request merged**
