### PR TITLE
Regions of Tyria Release v0.8.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/65928f30cda7610d9da6b66f0b43f4890e346626..512a44cc99c934846b0cab4eca719345d21854e2)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.regions_of_tyria_v0.8.0/Nekres.Regions_Of_Tyria-0.8.0.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Regions_Of_Tyria` == `Nekres.Regions_Of_Tyria`? |
| ✔️ | Manifest and package version match. | `0.8.0` == `0.8.0`? |
| ✔️ | Module and package checksum match. | `983D8121B02695B77387D3397A201A84DE35AD25D514ACFFACB8C92B04FF68D6` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** font size setting.

- **Added** font size feedback to the preview indicator.


- **Added** player speed threshold after which notifications are halted if the player speed is above it (Note: usually crossed when speeding using Griffon or Rollerbeetle.)



### Changes
- **Changed** preview setting indicator to show the current zone notification instead of a white rectangle.

- **Increased** internal notifications cooldown from 2 to 20 seconds during which notifications are halted.


### Bugfixes
- **Fixed** inaccurate sector detection (overlapping sectors as in Tangled Depths will still cause issues.)

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** font size setting.

- **Added** font size feedback to the preview indicator.


- **Added** player speed threshold after which notifications are halted if the player speed is above it *(Note: usually crossed when speeding using Griffon or Rollerbeetle.)*



### Changes
- **Changed** preview setting indicator to show the current zone notification instead of a white rectangle.

- **Increased** internal notifications cooldown from 2 to 20 seconds during which notifications are halted.


### Bugfixes
- **Fixed** inaccurate sector detection *(Note: overlapping sectors as in Tangled Depths will still cause issues.)*

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** font size setting.

- **Added** font size feedback to the preview indicator.


- **Added** player speed threshold after which notifications are halted if the player speed is above it&nbsp;*(Note: usually crossed when speeding using Griffon or Rollerbeetle.).*



### Changes
- **Changed** preview setting indicator to show the current zone notification instead of a white rectangle.

- **Increased** internal notifications cooldown from 2 to 20 seconds during which notifications are halted.


### Bugfixes
- **Fixed** inaccurate sector detection&nbsp;*(Note: overlapping sectors as in Tangled Depths will still cause issues.).*

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
