### PR TITLE
Regions of Tyria Release v0.9.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/9789afaa518209295332de5bf388d2c19c26ebaf..945661cdfb5a840a8935588dade323761743ace3)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.regions_of_tyria_v0.9.0/Nekres.Regions_Of_Tyria-0.9.0.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Regions_Of_Tyria` == `Nekres.Regions_Of_Tyria`? |
| ✔️ | Manifest and package version match. | `0.9.0` == `0.9.0`? |
| ✔️ | Module and package checksum match. | `529DF36779139A9F8AF8FF4BF282C84EE64E08A2A0251534796DC374784037F8` |

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting "Dissolve when Fading Out"

- **Added **a 200ms constant delay before revealing begins.

- **Added** underline to header text which spreads from the center to the edges of the header text


### Changes
- **Increased** line height to make a more clear separation of header from text.


### Bugfixes
- **Fixed **crash when a notification is being created when the module is about to unload.

- **Fixed** header text downscaling disproportionately when changing the Font Size.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting "Dissolve when Fading Out"

- **Added** a 200ms constant delay before revealing begins.


- **Added** underline to header text which spreads from the center to the edges of the header text


### Changes
- **Increased** line height to make a more clear separation of header from text.


### Bugfixes
- **Fixed **crash when a notification is being created when the module is about to unload.

- **Fixed** header text downscaling disproportionately when changing the Font Size.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting "Dissolve when Fading Out"

- **Added** a 200ms constant delay before revealing begins.


- **Added** underline to header text which spreads from the center to the edges of the header text


### Changes
- **Increased** line height to make a more clear separation of header from text.


### Bugfixes
- **Fixed** crash when a notification is being created when the module is about to unload.


- **Fixed** header text downscaling disproportionately when changing the Font Size.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting "Dissolve when Fading Out"

- **Added** a 200ms constant delay before revealing begins.


- **Added** underline to header text which spreads from the center to the edges.


### Changes
- **Increased** line height to make a more clear separation of header from text.


### Bugfixes
- **Fixed** crash when a notification is being created when the module is about to unload.


- **Fixed** header text downscaling disproportionately when changing the Font Size.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting "*Dissolve when Fading Out*".

- **Added** a 200ms constant delay before revealing begins.


- **Added** underline to header text which spreads from the center to the edges.


### Changes
- **Increased** line height to make a more clear separation of header from text.


### Bugfixes
- **Fixed** crash when a notification is being created when the module is about to unload.


- **Fixed** header text downscaling disproportionately when changing the Font Size.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting "*Dissolve when Fading Out*".

- **Added** a 200ms constant delay before revealing begins.


- **Added** underline to header text which spreads from the center to the edges.


### Changes
- **Increased** line height to make a more clear separation of header from text.


### Bugfixes
- **Fixed** crash when a notification is being created when the module is about to unload.


- **Fixed** header text downscaling disproportionately when changing the Font Size.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting "Dissolve when Fading Out".

- **Added** a 200ms constant delay before revealing begins.


- **Added** underline to header text which spreads from the center to the edges.


### Changes
- **Increased** line height to make a more clear separation of header from text.


### Bugfixes
- **Fixed** crash when a notification is being created when the module is about to unload.


- **Fixed** header text downscaling disproportionately when changing the Font Size.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting "Dissolve when Fading Out".

- **Added** notification pop to review changes made when toggling certain style settings.


- **Added** a 200ms constant delay before revealing begins.


- **Added** underline to header text which spreads from the center to the edges.


### Changes
- **Increased** line height to make a more clear separation of header from text.


### Bugfixes
- **Fixed** crash when a notification is being created when the module is about to unload.


- **Fixed** header text downscaling disproportionately when changing the Font Size.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting "Dissolve when Fading Out".

- **Added** notification pop to review changes made when toggling certain style settings.


- **Added** a 200ms constant delay before revealing begins.


- **Added** underline to header text which spreads from the center to the edges.


### Changes
- **Increased** line height to make a more clear separation of header from text.

- **Removed** Reveal Effect setting.


### Bugfixes
- **Fixed** crash when a notification is being created when the module is about to unload.


- **Fixed** header text downscaling disproportionately when changing the Font Size.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** setting "Dissolve when Fading Out".

- **Added** notification pop to review changes made when toggling certain style settings.


- **Added** a 200ms constant delay before revealing begins.


- **Added** underline to header text which spreads from the center to the edges.


### Changes
- **Increased** line height to make a more clear separation of header from text.

- **Removed** Reveal Effect setting.


### Bugfixes
- **Fixed** crash when a notification is being created when the module is about to unload.


- **Fixed** header text downscaling disproportionately when changing the Font Size.

- **Fixed**&nbsp;increasing memory usage when using the Font Size slider repeatedly.

**Pull request merged**
