### PR TITLE
Mistwar Release v1.4.2

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/0c5c91ddcc4d4fbb1cfd5f5eb899d2cff4177808..e95929bedda160ecc18e9bd68096d16c0dd55b8e)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.mistwar_v1.4.2/Nekres.Mistwar-1.4.2.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Mistwar` == `Nekres.Mistwar`? |
| ✔️ | Manifest and package version match. | `1.4.2` == `1.4.2`? |
| ✔️ | Module and package checksum match. | `60DBAD4B57AB7CDA61D24E6D7DD400A82FF4402547A92249B4F764450B228615` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- **Added** window for tactical map that can be resized and dragged.<br>

- **Removed** size setting of map.<br>

- **Removed** opacity setting of map.<br>

- **Removed** markers being force hidden when tactical map is opened.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- **Added** window for tactical map that can be resized and dragged.<br>- **Changed** player arrow to use avatar position instead of camera position. (Thanks, ArenaNet.👍)<br><br>

- **Removed** size setting of map.<br>

- **Removed** opacity setting of map.<br>

- **Removed** markers being force hidden when tactical map is opened.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

- **Added** window for tactical map that can be resized and dragged.&nbsp;&nbsp;<br>

- **Changed** player arrow to use avatar position instead of camera position. (Thanks, ArenaNet.👍)&nbsp;&nbsp;<br>

- **Removed** size setting of map.<br>

- **Removed** opacity setting of map.<br>

- **Removed** markers being force hidden when tactical map is opened.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** window for tactical map that can be resized and dragged.


### Changes
- **Changed** player arrow to use avatar position instead of camera position. (Thanks, ArenaNet.👍)

- **Removed** size setting of map.

- **Removed** opacity setting of map.

- **Removed** markers being force hidden when tactical map is opened.

**Pull request merged**
