### PR TITLE
Mount Music Release v1.2.4

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/0ffd77ed17a80a3dfcefe093208796a4145767ae..d0b3719a987e178195d5eb14fddec0ca09146e99)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.music_mixer_v1.2.4/Nekres.Music_Mixer-1.2.4.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Music_Mixer` == `Nekres.Music_Mixer`? |
| ✔️ | Manifest and package version match. | `1.2.4` == `1.2.4`? |
| ✔️ | Module and package checksum match. | `B17FD4C59091D1B9FFB1E3353F0E455E8F0DD0DE064FB7AD5995C65CD270E3F6` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Fix
- Fixed volume slider resetting to 50% if above 50%.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Fix
- Fixed volume slider resetting to 50% if set above 50%.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Fix
- **Fixed** volume slider resetting to 50% if set above 50%.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Bugfix
- **Fixed** volume slider resetting to 50% if set above 50%.

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
