### PR TITLE
Event Table Release v3.15.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Estreya

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/a8da53c21305c520e7b32ef62669a2185a7788b2..7d6c2ab11105d65f741c196cca3ed8a8ed234915)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/estreya.bh.eventtable_v3.15.0/estreya.bh.eventTable-3.15.0.bhm |
| ✔️ | Manifest and package namespace match. | `estreya.bh.eventTable` == `estreya.bh.eventTable`? |
| ✔️ | Manifest and package version match. | `3.15.0` == `3.15.0`? |
| ✔️ | Module and package checksum match. | `57A7B943751D76CC2F2F3323B1DC058A16FD5888BA0C907878142AE5D6543001` |

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Bugfixes**<br>

- Fixed inconsistency with error state display

- Fixed json date parsing for exotic windows calendar settings

- Fixed crash for missing key in dictionary


**Features**<br>

- Added option to hide area after successful waypoint navigation

- Added color options for event timers

- Added keybindings to show/hide dynamic events and event timers


**New Feature - Self Hosting Events**<br>

The new big feature of event table is here!<br>You are running an event and are still missing people?<br>Mark your event as hosting in the module and let people discover it.<br>

The module will show you if you are on the same map instance as the hoster.<br>

You can use the auto wispher feature to ask for a quick invite to a group/squad.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Bugfixes**<br>

- Fixed inconsistency with error state display

- Fixed json date parsing for exotic windows calendar settings

- Fixed crash for missing key in dictionary


**Features**<br>

- Added option to hide area after successful waypoint navigation

- Added color options for event timers

- Added keybindings to show/hide dynamic events and event timers


**New Feature - Self Hosting Events**<br>

The new big feature of event table is here!<br>You are running an event and are still missing people?<br>Mark your event as hosting in the module and let people discover it.<br>

The module will show you if you are on the same map instance as the hoster.<br>

You can use the auto wispher feature to ask for a quick invite to a group/squad.<br>

**Info for WINE users**<br>

The usage of the module on WINE as provided via the normal blish repo causes blish to crash.<br>

The reason for that is the usage of the windows foundation universal api contract for OS notifications which is not fully implemented in WINE.<br>

If you want to use the module on WINE please use this custom build: [CLICK HERE](https://files.estreya.de/blish-hud/event-table/releases/Estreya.BlishHUD.EventTable_3.15.0-WINE.bhm)<br>

*You CAN'T use the update feature for modules when using that custom build.*<br>

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Bugfixes**<br>

- Fixed inconsistency with error state display

- Fixed json date parsing for exotic windows calendar settings

- Fixed crash for missing key in dictionary


**Features**<br>

- Added option to hide area after successful waypoint navigation

- Added color options for event timers

- Added keybindings to show/hide dynamic events and event timers


**Others**<br>

- Temporary disabled message container to show automatically.


**New Feature - Self Hosting Events**<br>

The new big feature of event table is here!<br>You are running an event and are still missing people?<br>Mark your event as hosting in the module and let people discover it.<br>

The module will show you if you are on the same map instance as the hoster.<br>

You can use the auto wispher feature to ask for a quick invite to a group/squad.<br>

Do not abuse the system! You can be reported by other players.<br>Likewise, the abuse of the report system will not be tolerated.<br>

**Info for WINE users**<br>

The usage of the module on WINE as provided via the normal blish repo causes blish to crash.<br>

The reason for that is the usage of the windows foundation universal api contract for OS notifications which is not fully implemented in WINE.<br>

If you want to use the module on WINE please use this custom build: [CLICK HERE](https://files.estreya.de/blish-hud/event-table/releases/Estreya.BlishHUD.EventTable_3.15.0-WINE.bhm)<br>

*You CAN'T use the update feature for modules when using that custom build.*<br>

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
