### PR TITLE
Stream Out Release v0.7.8

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/5f223486756202736bf9be810e7a7112092ffa70..9c4eaf416792881fa2401440e3ca13b5c0575437)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.stream_out_v0.7.8/Nekres.Stream_Out-0.7.8.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Stream_Out` == `Nekres.Stream_Out`? |
| ✔️ | Manifest and package version match. | `0.7.8` == `0.7.8`? |
| ✔️ | Module and package checksum match. | `F909AD17A34BEB0F698691210C27A0E978BAA47B4319FC96D988B0390D757CA9` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

• Add character\_name.txt<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

• Added ``character_name.txt`` as export.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

• Added ``profession_name.txt`` as export.<br>

**Pull request merged**
