### PR TITLE
Guild Missions 1.0.0

### PR DESCRIPTION
**Pull request by entrhopi**
- Some fixes with treks
- Clipboard import/export of saved treks
- Wiki links
- All missions now available (thank you Harriss)

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/7f195c9282a7ba58494d56642e0737bfe3aba53f..5673ee1d36fffaa911c699af39b0066346e7f8c6)
## Automated Validation Status
⚠️ **Failed Validation - See Below for Details**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/entrhopi/Blish-HUD-Guild-Missions/releases/download/v1.0.0/Guild-Missions.bhm |
| ✔️ | Manifest and package namespace match. | `entrhopi.Guild_Missions` == `entrhopi.Guild_Missions`? |
| ✔️ | Manifest and package version match. | `1.0.0` == `1.0.0`? |
| ❌ | Module and package checksums do not match! | Manifest indicated `0dd761308ec8d5337a1c0cb21b4a1d488338bb450109c13985857de64c5a4940` but got `0DD761308EC8D5337A1C0CB21B4A1D488338BB450109C13985857DE64C5A4940` instead. |

**Comment by dlamkins** [comment]
Well, a bit silly that our review script isn't comparing with case ignored for the checksum, but how did you manage to get a lowercase checksum in there?  I believe the script generates it all uppercase or did you just build it by hand?

**Comment by BlishHUD** [comment]
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/entrhopi/Blish-HUD-Guild-Missions/releases/download/v1.0.0/Guild-Missions.bhm |
| ✔️ | Manifest and package namespace match. | `entrhopi.Guild_Missions` == `entrhopi.Guild_Missions`? |
| ✔️ | Manifest and package version match. | `1.0.0` == `1.0.0`? |
| ✔️ | Module and package checksum match. | `0DD761308EC8D5337A1C0CB21B4A1D488338BB450109C13985857DE64C5A4940` |

**Review by dlamkins — APPROVED** [review]

**Comment by entrhopi** [comment]
> 

It's all handcrafted atm. 🙈

**Pull request merged**
