### PR TITLE
Clears Tracker Release v3.1.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Soeed

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/c7e258a84102cc7c11b54919958452d45b5ae6d8..2d4b2ff43fa3c6595dd904eed1492a7670b85857)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/soeed.raidclears_v3.1.1/Soeed.RaidClears-3.1.1.bhm |
| ✔️ | Manifest and package namespace match. | `Soeed.RaidClears` == `Soeed.RaidClears`? |
| ✔️ | Manifest and package version match. | `3.1.1` == `3.1.1`? |
| ✔️ | Module and package checksum match. | `5BF7D32C9807CA7F610345F3E5530132AB99D65315822A16B6037B84FE42285B` |

**Comment by a727891** [comment]
sorry, an idea-in-progress was visible on the module settings view

**Comment by BlishHUD** [comment]
Release notes updated by Soeed.<br><br>
New Features<br>

Wing 8 / Mount Balrior added to raid tracking!<br>

Known issue:<br>

If you use `anchorStrikesToRaid` option, turn it off and back on or move the raid panel slightly to realign the overlays.<br>

**Comment by dlamkins** [comment]
@a727891 lol, no worries!

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
