### PR TITLE
Trading Post Watcher Release v1.1.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Estreya

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/859591bb40959a9bb98ef1ac7d94623fba175561..55d3173c977038b27ed93369de89d4de1b03d9f1)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/estreya.bh.tradingpostwatcher_v1.1.1/estreya.bh.tradingPostWatcher-1.1.1.bhm |
| ✔️ | Manifest and package namespace match. | `estreya.bh.tradingPostWatcher` == `estreya.bh.tradingPostWatcher`? |
| ✔️ | Manifest and package version match. | `1.1.1` == `1.1.1`? |
| ✔️ | Module and package checksum match. | `22444C0BB483EA834DB0BCAA5A555100D69A7104207D86D339083F48A64D8CF8` |

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Bugfixes:**<br>

- Added missing implementation of the following options:Enabled KeybindingShow Highest TransactionsShow Tooltips

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Bugfixes:**<br>

- Added missing implemention of the following options:
- Enabled Keybinding
- Show Tooltips
- Show Highest Transactions

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**Bugfixes:**<br>

- Added missing implemention of the following options:
Enabled Keybinding
Show Tooltips
Show Highest Transactions

**Pull request merged**
