### PR TITLE
Decor Release v1.2.2

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Terter

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/e6377b0c33166da6a22532aef406d7e17d0d053a..ca964b2e7d6241de5e7e9ac5fabdacf0da29d8b1)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/bh.decor.decormodule_v1.2.2/bh.decor.decormodule-1.2.2.bhm |
| ✔️ | Manifest and package namespace match. | `bh.decor.decormodule` == `bh.decor.decormodule`? |
| ✔️ | Manifest and package version match. | `1.2.2` == `1.2.2`? |
| ✔️ | Module and package checksum match. | `C7176BF1708988F9E51C599B0274735F2B86E3ECADA7B3C4462540579B7B4636` |

**Comment by BlishHUD** [comment]
Release notes updated by Terter.<br><br>
### Decor 1.2.2
- Fixed the corner icon's loading spinner that was appearing on top of the Blish Hud icon after the activation of the Decor module.

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Terter.<br><br>
### Decor 1.2.2
- Fixed the corner icon's loading spinner that was appearing on top of the Blish Hud icon after the activation of the Decor module.


- Optimized the code to take less physical mrmory. The module should be running faster on slower machines now.

**Comment by BlishHUD** [comment]
Release notes updated by Terter.<br><br>
### Decor 1.2.2
- Fixed the corner icon's loading spinner that was appearing on top of the Blish Hud icon after the activation of the Decor module.


- Optimize the code to take less physical memory. The module should be running faster on slower machines now.

**Pull request merged**
