### PR TITLE
Session Tracker Release v3.0.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Ecksofa

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/c0a6856ce280c6dc3a468a95f195c4f31165c2f0..5bedde379a3bb1a7a4297bcf2ead6f48b1e52eb7)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/ecksofa.sessiontracker_v3.0.0/ecksofa.sessiontracker-3.0.0.bhm |
| ✔️ | Manifest and package namespace match. | `ecksofa.sessiontracker` == `ecksofa.sessiontracker`? |
| ✔️ | Manifest and package version match. | `3.0.0` == `3.0.0`? |
| ✔️ | Module and package checksum match. | `AED085CA11613588A0A336768867B90E8F1CF3B76F99A0F84FEAE956172ABA26` |

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**Fixed**<br>

- on blish startup the stats window sometimes automatically moved into a screen border which matched the windowAnchor position.<br>

**Internal**<br>

- added Debug logging for the case users have to reproduce a bug with debug enabled (module version, module settings, gw/blish interface size)<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**Fixed**<br>

- on
blish startup the stats window sometimes automatically moved into a screen
border which matched the windowAnchor position.<br>

**Internal**<br>

- added
Debug logging for the case users have to reproduce a bug with debug enabled
(module version, module settings, gw/blish interface size)<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
**Fixed**<br>

- on blish startup the stats window sometimes automatically moved into a screen border which matched the windowAnchor position.<br>

**Internal**<br>

- added Debug logging for the case users have to reproduce a bug with debug enabled (module version, module settings, gw/blish interface size)<br>

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
