### PR TITLE
Proof Logix Release v2.21.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/08b4a5b8a768712ea6e73c5e04993e79d94460d0..5674d48e5461a8631c2f6a6e9a75ccb194efa480)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/killproofmodule_v2.21.1/KillProofModule-2.21.1.bhm |
| ✔️ | Manifest and package namespace match. | `KillProofModule` == `KillProofModule`? |
| ✔️ | Manifest and package version match. | `2.21.1` == `2.21.1`? |
| ✔️ | Module and package checksum match. | `67D54905119840A8D9F50841C4A1F890B43F274AA58E0447930B6D20C39563B0` |

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

• Fixed services waiting for icons from the Gw2WebAPI.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What's Changed**<br>

• Fixed services waiting for profession icons from the GW2 API.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Hotifx
- **Fixed** services waiting for profession icons from the GW2 API.

**Pull request merged**
