### PR TITLE
Portal Distance Release v1.0.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Estreya

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/7f195c9282a7ba58494d56642e0737bfe3aba53f..8e0a9059447884baf222f9b477ea1e5bf167bb48)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/estreya.bh.portaldistance_v1.0.0/estreya.bh.portalDistance-1.0.0.bhm |
| ✔️ | Manifest and package namespace match. | `estreya.bh.portalDistance` == `estreya.bh.portalDistance`? |
| ✔️ | Manifest and package version match. | `1.0.0` == `1.0.0`? |
| ✔️ | Module and package checksum match. | `ACFD771E993146938743B4F404E8B52C5C99C4575FC51A176F499174902D5DC0` |

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**First release of the new Portal Distance module!**<br>

The module shows the current distance to your portal entrances.<br>Works best with the arc dps integration as portal usage can be auto detected.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**First release of the new Portal Distance module!**<br>

The module shows the current distance to your portal entrances.<br>Works best with the arc dps integration as portal usage can be auto detected.<br>

*Does not work in competitive mode.*<br>

**Comment by BlishHUD** [comment]
Release notes updated by Estreya.<br><br>
**First release of the new Portal Distance module!**<br>

The module shows the current distance to your portal entrances.<br>Works best with the arc dps integration as portal usage can be auto detected.<br>

*Disabled in competitive mode.*<br>

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
