### PR TITLE
Mount Music Release v1.8.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/c8b7218ee3b8867a3b0fe3cc19d860df0a355343..b2366d6065d381c513505d5dc777529d0a4c486e)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/nekres.music_mixer_v1.8.1/Nekres.Music_Mixer-1.8.1.bhm |
| ✔️ | Manifest and package namespace match. | `Nekres.Music_Mixer` == `Nekres.Music_Mixer`? |
| ✔️ | Manifest and package version match. | `1.8.1` == `1.8.1`? |
| ✔️ | Module and package checksum match. | `1C48A58D0CB0FE19E574560283F4C3806F4EA34929AACBDDE9DF35CC4511FDD3` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** "Next" button.

- **Added** log entry for loaded song.


- *(v1.8.0) ***Added**&nbsp;setting "Play to completion" which makes the current song continue after dismounting until its end.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** "Next" button (stops the song if dismounted and 'Play to Completion' is enabled).

- **Added** log entry for loaded song.


- *(v1.8.0) ***Added**&nbsp;setting "Play to completion" which makes the current song continue after dismounting until its end.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Features
- **Added** "Next" button which will stop the current song and play another one if the player's state fits any playlist.


- **Added** log entry for loaded song.

- **Added**&nbsp;setting "Play to completion" which will finish the current song even after dismounting.

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
