### PR TITLE
Proof Logix Release v2.21.5

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Nekres

### CODE REVIEW

**Comment by BlishHUD** [comment]
[View Source](https://github.com/dlamkins/bhud-module-src-test/compare/bb066aca2ec90e0e881c40f01a079ce021d1549c..f8af1acb37bf61d3e2f132278959b952b55e2e91)
## Automated Validation Status
✔️ **Ready for Manual Approval**
## Automated Tests
| Result | Test | Details |
|-|-|-|
| ✔️ | Module URL is valid. | https://github.com/blish-hud/bhud-modules/releases/download/killproofmodule_v2.21.5/KillProofModule-2.21.5.bhm |
| ✔️ | Manifest and package namespace match. | `KillProofModule` == `KillProofModule`? |
| ✔️ | Manifest and package version match. | `2.21.5` == `2.21.5`? |
| ✔️ | Module and package checksum match. | `9691C05568A3FED2177AA3DD8143E3684D5C412E90DFB926B00312EF9E15D837` |

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
**What’s Changed**<br>

• Fixed missing permissions alert not working.<br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Hotfix
- **Fixed** missing permissions alert not working.

**Comment by BlishHUD** [comment]
Release notes updated by Nekres.<br><br>
### Hotifx
- **Fixed** missing permissions alert not working.

**Pull request merged**
